In [426]:
import pandas as pd
import numpy as np

In [379]:
df = pd.read_csv('./cnp 3-yrs_web-scrap.csv')
df

,Unnamed: 0,P-ASP Date,Building / Address,Floor,Unit,GFA (ft??),SA (ft??),Leased / Sold,Price(HK$),Price/ft2(GFA),Price/ft2(SA),Source
0,3.0,30/4/2022,Yau Tong??,23,E,857,687,Leased,"20,000",@23,@29,CENTURY 21 HOME-LY PROPERTY AGENCY
1,4.0,30/4/2022,Yau Tong??,18,B,644,517,Leased,"15,000",@23,@29,CENTURY 21 HOME-LY PROPERTY AGENCY
2,5.0,30/4/2022,Yau Tong??,25,A,939,748,Leased,"21,500",@23,@29,CENTURY 21 HOME-LY PROPERTY AGENCY
3,6.0,30/4/2022,Yau Tong??,22,H,939,748,Leased,"20,500",@22,@27,CENTURY 21 HOME-LY PROPERTY AGENCY
4,7.0,30/4/2022,Yau Tong??,7,C,664,522,Leased,"16,500",@25,@32,CENTURY 21 HOME-LY PROPERTY AGENCY
...,...,...,...,...,...,...,...,...,...,...,...,...
5068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [380]:
df.columns

Index(['Unnamed: 0', 'P-ASP Date', 'Building / Address', 'Floor', 'Unit',
       'GFA (ft??)', 'SA (ft??)', 'Leased / Sold', 'Price(HK$)',
       'Price/ft2(GFA)', 'Price/ft2(SA)', 'Source'],
      dtype='object')

In [381]:
df = df.drop(columns=['Unnamed: 0','GFA (ft??)','Leased / Sold','Price/ft2(GFA)','Source','Unit'], axis=1)

df

     P-ASP Date Building / Address Floor SA (ft??) Price(HK$) Price/ft2(SA)
0     30/4/2022         Yau Tong??    23       687     20,000           @29
1     30/4/2022         Yau Tong??    18       517     15,000           @29
2     30/4/2022         Yau Tong??    25       748     21,500           @29
3     30/4/2022         Yau Tong??    22       748     20,500           @27
4     30/4/2022         Yau Tong??     7       522     16,500           @32
...         ...                ...   ...       ...        ...           ...
5068        NaN                NaN   NaN       NaN        NaN           NaN
5069        NaN                NaN   NaN       NaN        NaN           NaN
5070        NaN                NaN   NaN       NaN        NaN           NaN
5071        NaN                NaN   NaN       NaN        NaN           NaN
5072        NaN                NaN   NaN       NaN        NaN           NaN

[5073 rows x 6 columns]

In [382]:
df = df.dropna(axis=0)
df

,P-ASP Date,Building / Address,Floor,SA (ft??),Price(HK$),Price/ft2(SA)
0,30/4/2022,Yau Tong??,23,687,"20,000",@29
1,30/4/2022,Yau Tong??,18,517,"15,000",@29
2,30/4/2022,Yau Tong??,25,748,"21,500",@29
3,30/4/2022,Yau Tong??,22,748,"20,500",@27
4,30/4/2022,Yau Tong??,7,522,"16,500",@32
...,...,...,...,...,...,...
550,6/10/2021,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,15,517,"16,300",@32
552,5/10/2021,Tseung Kwan O??METRO CITY PH 01 TWR 02,H,364,"15,000",@41
553,5/10/2021,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),L,484,"14,500",@30
554,5/10/2021,Tseung Kwan O??THE BEAUMOUNT TWR 06,H,501,"15,500",@31
555,5/10/2021,Aberdeen??JADEWATER ...,??????,519,"21,000",@40

In [383]:
df.columns

Index(['P-ASP Date', 'Building / Address', 'Floor', 'SA (ft??)', 'Price(HK$)',
       'Price/ft2(SA)'],
      dtype='object')

In [384]:
df.dtypes

P-ASP Date            object
Building / Address    object
Floor                 object
SA (ft??)             object
Price(HK$)            object
Price/ft2(SA)         object
dtype: object

In [385]:
df = df.rename(columns={"P-ASP Date": "Date", "SA (ft??)": "SA (ft2)"})

In [386]:
df["Date"] = pd.to_datetime(df["Date"],dayfirst=True,exact=False)
df

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA)
0,2022-04-30,Yau Tong??,23,687,"20,000",@29
1,2022-04-30,Yau Tong??,18,517,"15,000",@29
2,2022-04-30,Yau Tong??,25,748,"21,500",@29
3,2022-04-30,Yau Tong??,22,748,"20,500",@27
4,2022-04-30,Yau Tong??,7,522,"16,500",@32
...,...,...,...,...,...,...
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,15,517,"16,300",@32
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,H,364,"15,000",@41
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),L,484,"14,500",@30
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,H,501,"15,500",@31
555,2021-10-05,Aberdeen??JADEWATER ...,??????,519,"21,000",@40

In [387]:
for i in df.Date:
    print(i)

2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-30 00:00:00
2022-04-29 00:00:00
2022-04-29 00:00:00
2022-04-29 00:00:00
2022-04-29 00:00:00
2022-04-29 00:00:00
2022-04-27 00:00:00
2022-04-26 00:00:00
2022-04-26 00:00:00
2022-04-26 00:00:00
2022-04-25 00:00:00
2022-04-25 00:00:00
2022-04-25 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-24 00:00:00
2022-04-23 00:00:00
2022-04-23 00:00:00
2022-04-23 00:00:00
2022-04-22 00:00:00
2022-04-22 00:00:00
2022-04-22 00:00:00
2022-04-22 00:00:00
2022-04-21 00:00:00
2022-04-21 00:00:00
2022-04-19 00:00:00
2022-04-18 00:00:00
2022-04-18 00:00:00
2022-04-18 00:00:00
2022-04-17 00:00:00
2022-04-17 00:00:00
2022-04-17 00:00:00
2022-04-17 00:00:00
2022-04-16 00:00:00
2022-04-16 00:00:00
2022-04-15 00:00:00
2022-04-15 00:00:00
2022-04-15 00:00:00
2022-04-15 00:00:00
2022-04-14 00:00:00
2022-04-09 00:00:00
2022-04-09 00:00:00
2022-04-09 00:00:00
2022-04-09 00:00:00
2022-04-09 00:00:00
2022-04-07 00:00:00
2022-04-07 00:00:00
2022-04-07 00:00:00
2022-04-07 00:00:00
2022-04-07 00:00:00
2022-04-07 00:00:00
2022-04-07 00:00:00
2022-04-06 00:00:00
2022-04-06 00:00:00
2022-04-06 00:00:00
2022-04-05 00:00:00
2022-04-05 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-01 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-03-23 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-20 00:00:00
2022-03-20 00:00:00
2022-03-20 00:00:00
2022-03-20 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-12 00:00:00
2022-03-11 00:00:00
2022-03-11 00:00:00
2022-03-10 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-01 00:00:00
2022-03-01 00:00:00
2022-03-01 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-27 00:00:00
2022-02-27 00:00:00
2022-02-25 00:00:00
2022-02-25 00:00:00
2022-02-25 00:00:00
2022-02-25 00:00:00
2022-02-25 00:00:00
2022-02-24 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-21 00:00:00
2022-02-21 00:00:00
2022-02-20 00:00:00
2022-02-20 00:00:00
2022-02-20 00:00:00
2022-02-19 00:00:00
2022-02-19 00:00:00
2022-02-19 00:00:00
2022-02-19 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-02-17 00:00:00
2022-02-16 00:00:00
2022-02-16 00:00:00
2022-02-15 00:00:00
2022-02-15 00:00:00
2022-02-15 00:00:00
2022-02-15 00:00:00
2022-02-15 00:00:00
2022-02-14 00:00:00
2022-02-14 00:00:00
2022-02-13 00:00:00
2022-02-13 00:00:00
2022-02-13 00:00:00
2022-02-13 00:00:00
2022-02-13 00:00:00
2022-02-13 00:00:00
2022-02-13 00:00:00
2022-02-12 00:00:00
2022-02-12 00:00:00
2022-02-11 00:00:00
2022-02-09 00:00:00
2022-02-08 00:00:00
2022-02-08 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-02-06 00:00:00
2022-02-06 00:00:00
2022-02-05 00:00:00
2022-02-05 00:00:00
2022-02-05 00:00:00
2022-02-05 00:00:00
2022-02-05 00:00:00
2022-02-05 00:00:00
2022-02-04 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-30 00:00:00
2022-01-30 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-01-28 00:00:00
2022-01-27 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-01-25 00:00:00
2022-01-24 00:00:00
2022-01-23 00:00:00
2022-01-23 00:00:00
2022-01-23 00:00:00
2022-01-23 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-01-19 00:00:00
2022-01-18 00:00:00
2022-01-18 00:00:00
2022-01-17 00:00:00
2022-01-17 00:00:00
2022-01-17 00:00:00
2022-01-16 00:00:00
2022-01-16 00:00:00
2022-01-16 00:00:00
2022-01-16 00:00:00
2022-01-15 00:00:00
2022-01-15 00:00:00
2022-01-15 00:00:00
2022-01-15 00:00:00
2022-01-13 00:00:00
2022-01-13 00:00:00
2022-01-13 00:00:00
2022-01-13 00:00:00
2022-01-13 00:00:00
2022-01-12 00:00:00
2022-01-12 00:00:00
2022-01-12 00:00:00
2022-01-11 00:00:00
2022-01-10 00:00:00
2022-01-10 00:00:00
2022-01-09 00:00:00
2022-01-09 00:00:00
2022-01-09 00:00:00
2022-01-09 00:00:00
2022-01-09 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-01-07 00:00:00
2022-01-07 00:00:00
2022-01-07 00:00:00
2022-01-06 00:00:00
2022-01-06 00:00:00
2022-01-05 00:00:00
2022-01-05 00:00:00
2022-01-05 00:00:00
2022-01-04 00:00:00
2022-01-04 00:00:00
2022-01-04 00:00:00
2022-01-03 00:00:00
2022-01-03 00:00:00
2022-01-03 00:00:00
2022-01-03 00:00:00
2022-01-03 00:00:00
2022-01-03 00:00:00
2022-01-02 00:00:00
2022-01-01 00:00:00
2022-01-01 00:00:00
2022-01-01 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-31 00:00:00
2021-12-30 00:00:00
2021-12-29 00:00:00
2021-12-28 00:00:00
2021-12-26 00:00:00
2021-12-26 00:00:00
2021-12-26 00:00:00
2021-12-25 00:00:00
2021-12-24 00:00:00
2021-12-23 00:00:00
2021-12-22 00:00:00
2021-12-22 00:00:00
2021-12-21 00:00:00
2021-12-21 00:00:00
2021-12-20 00:00:00
2021-12-19 00:00:00
2021-12-18 00:00:00
2021-12-18 00:00:00
2021-12-18 00:00:00
2021-12-18 00:00:00
2021-12-17 00:00:00
2021-12-17 00:00:00
2021-12-17 00:00:00
2021-12-16 00:00:00
2021-12-16 00:00:00
2021-12-16 00:00:00
2021-12-15 00:00:00
2021-12-15 00:00:00
2021-12-14 00:00:00
2021-12-14 00:00:00
2021-12-14 00:00:00
2021-12-13 00:00:00
2021-12-13 00:00:00
2021-12-13 00:00:00
2021-12-12 00:00:00
2021-12-11 00:00:00
2021-12-11 00:00:00
2021-12-10 00:00:00
2021-12-10 00:00:00
2021-12-08 00:00:00
2021-12-07 00:00:00
2021-12-07 00:00:00
2021-12-07 00:00:00
2021-12-07 00:00:00
2021-12-06 00:00:00
2021-12-06 00:00:00
2021-12-05 00:00:00
2021-12-05 00:00:00
2021-12-05 00:00:00
2021-12-04 00:00:00
2021-12-04 00:00:00
2021-12-04 00:00:00
2021-12-04 00:00:00
2021-12-03 00:00:00
2021-11-30 00:00:00
2021-11-29 00:00:00
2021-11-29 00:00:00
2021-11-29 00:00:00
2021-11-29 00:00:00
2021-11-29 00:00:00
2021-11-29 00:00:00
2021-11-28 00:00:00
2021-11-28 00:00:00
2021-11-28 00:00:00
2021-11-28 00:00:00
2021-11-27 00:00:00
2021-11-27 00:00:00
2021-11-27 00:00:00
2021-11-27 00:00:00
2021-11-26 00:00:00
2021-11-26 00:00:00
2021-11-26 00:00:00
2021-11-24 00:00:00
2021-11-22 00:00:00
2021-11-22 00:00:00
2021-11-21 00:00:00
2021-11-21 00:00:00
2021-11-20 00:00:00
2021-11-20 00:00:00
2021-11-20 00:00:00
2021-11-20 00:00:00
2021-11-19 00:00:00
2021-11-19 00:00:00
2021-11-19 00:00:00
2021-11-17 00:00:00
2021-11-17 00:00:00
2021-11-16 00:00:00
2021-11-15 00:00:00
2021-11-15 00:00:00
2021-11-15 00:00:00
2021-11-14 00:00:00
2021-11-13 00:00:00
2021-11-13 00:00:00
2021-11-13 00:00:00
2021-11-13 00:00:00
2021-11-11 00:00:00
2021-11-10 00:00:00
2021-11-10 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-09 00:00:00
2021-11-07 00:00:00
2021-11-07 00:00:00
2021-11-07 00:00:00
2021-11-07 00:00:00
2021-11-07 00:00:00
2021-11-06 00:00:00
2021-11-06 00:00:00
2021-11-06 00:00:00
2021-11-04 00:00:00
2021-11-04 00:00:00
2021-11-04 00:00:00
2021-11-03 00:00:00
2021-11-03 00:00:00
2021-11-03 00:00:00
2021-11-03 00:00:00
2021-11-03 00:00:00
2021-11-03 00:00:00
2021-11-03 00:00:00
2021-11-01 00:00:00
2021-11-01 00:00:00
2021-10-31 00:00:00
2021-10-31 00:00:00
2021-10-31 00:00:00
2021-10-31 00:00:00
2021-10-30 00:00:00
2021-10-30 00:00:00
2021-10-29 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-26 00:00:00
2021-10-25 00:00:00
2021-10-25 00:00:00
2021-10-25 00:00:00
2021-10-24 00:00:00
2021-10-23 00:00:00
2021-10-23 00:00:00
2021-10-22 00:00:00
2021-10-22 00:00:00
2021-10-22 00:00:00
2021-10-21 00:00:00
2021-10-21 00:00:00
2021-10-21 00:00:00
2021-10-21 00:00:00
2021-10-20 00:00:00
2021-10-20 00:00:00
2021-10-19 00:00:00
2021-10-19 00:00:00
2021-10-19 00:00:00
2021-10-19 00:00:00
2021-10-18 00:00:00
2021-10-18 00:00:00
2021-10-18 00:00:00
2021-10-18 00:00:00
2021-10-18 00:00:00
2021-10-18 00:00:00
2021-10-17 00:00:00
2021-10-17 00:00:00
2021-10-17 00:00:00
2021-10-17 00:00:00
2021-10-16 00:00:00
2021-10-16 00:00:00
2021-10-15 00:00:00
2021-10-15 00:00:00
2021-10-15 00:00:00
2021-10-14 00:00:00
2021-10-14 00:00:00
2021-10-14 00:00:00
2021-10-14 00:00:00
2021-10-13 00:00:00
2021-10-13 00:00:00
2021-10-13 00:00:00
2021-10-12 00:00:00
2021-10-12 00:00:00
2021-10-11 00:00:00
2021-10-11 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-10 00:00:00
2021-10-08 00:00:00
2021-10-08 00:00:00
2021-10-08 00:00:00
2021-10-07 00:00:00
2021-10-07 00:00:00
2021-10-07 00:00:00
2021-10-06 00:00:00
2021-10-06 00:00:00
2021-10-05 00:00:00
2021-10-05 00:00:00
2021-10-05 00:00:00
2021-10-05 00:00:00

In [377]:
for i in df["Building / Address"]:
    print(i)

Yau Tong??
Yau Tong??
Yau Tong??
Yau Tong??
Yau Tong??
Yau Tong??
Yau Tong??
Yau Tong??
Yau Tong??
Tseung Kwan O??LOHAS PARK PH 07A MONTARA TWR 02A
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 01
Tseung Kwan O??NAN FUNG PLAZA TWR 02
Aberdeen??ON TAI BLDG
Tseung Kwan O??METRO CITY PH 02 TWR 07
Tseung Kwan O??NAN FUNG PLAZA TWR 06
Tseung Kwan O??NAN FUNG PLAZA TWR 02
Tseung Kwan O??BEVERLY GDN PH 01 BLK 01 (PSPS)
Tseung Kwan O??THE BEAUMOUNT TWR 07
Tseung Kwan O??THE WINGS IIIA TWR 05A
Tseung Kwan O??CORINTHIA BY THE SEA TWR 02
Aberdeen??ABERDEEN CTR BLK I KONG WING COURT
Aberdeen??ALBERT HSE
Aberdeen??FORTUNE MAN
Yau Tong??
Tseung Kwan O??CHOI MING COURT BLK E (HOS)
Tseung Kwan O??METRO CITY PH 02 TWR 10
Tseung Kwan O??METRO CITY PH 02 TWR 11
Tseung Kwan O??CHOI MING COURT BLK E (HOS)
Tseung Kwan O??FINERY PARK BLK 01
Tseung Kwan O??METRO CITY PH 02 TWR 10
Aberdeen??ABERDEEN CTR BLK B HOI CHU COURT
Aberdeen??KAM FAT BLDG
Aberdeen??MARINA HABITAT BLK 02 (SCHS)
Aberdeen??SOUTH COAST
Aberdeen??ABERDEEN CTR BLK T KWUN CHIU COURT
Yau Tong??
Tseung Kwan O??THE PAPILLONS TWR 05
Tseung Kwan O??HIN MING COURT (HOS)
Aberdeen??YUE FAI COURT BLK B (HOS)
Aberdeen??ABERDEEN CTR BLK J KONG HING COURT
Tseung Kwan O??CHUNG MING COURT BLK B FAI MING HSE (HOS
Tseung Kwan O??TONG MING COURT BLK C (HOS)
Tseung Kwan O??YAN MING COURT BLK D (HOS)
Tseung Kwan O??PARK CENTRAL PH 02 TWR 02
Tseung Kwan O??OCEAN WINGS TWR 07A
Yau Tong??LAGUNA CITY PH 04 BLK 09
Tseung Kwan O??PARK CENTRAL PH 03 TWR 13
Tseung Kwan O??METRO CITY PH 02 TWR 05
Tseung Kwan O??BEVERLY GDN PH 01 BLK 03 (PSPS)
Tseung Kwan O??METRO CITY PH 01 TWR 02
Tseung Kwan O??TONG MING COURT BLK B (HOS)
Tseung Kwan O??KING MING COURT BLK A HEI KING HSE (HOS)
Tseung Kwan O??EAST POINT CITY BLK 02
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen??COBLE COURT
Wong Chuk Hang??JUMBO COURT
Tseung Kwan O??VERBENA HTS BLK 03 (FSS)
Tseung Kwan O??METRO CITY PH 02 TWR 09
Tseung Kwan O??VERBENA HTS BLK 05 (FSS)
Tseung Kwan O??PO MING COURT BLK B (HOS)
Tseung Kwan O??RADIANT TWRS BLK 02 (SCHS)
Yau Tong??LAGUNA CITY PH 03 BLK 36
Yau Tong??LAGUNA CITY PH 03 BLK 36
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 01 TWR 3A
Tseung Kwan O??ON NING GDN BLK 01 (PSPS)
Tseung Kwan O??GRANDIOSE BLK 03
Aberdeen??H BONAIRE
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 05
Aberdeen??YUE ON COURT BLK D (HOS)
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O??WELL ON GDN BLK 02
Tseung Kwan O??VERBENA HTS BLK 05 (FSS)
Tseung Kwan O??PARK CENTRAL PH 02 TWR 12
Tseung Kwan O??THE WINGS IIIA TWR 05A
Tseung Kwan O??THE WINGS TWR 03 LUNA DIAMOND
Tseung Kwan O??THE WINGS II TWR 05B
Yau Tong??LAGUNA CITY PH 02 BLK 24
Tseung Kwan O??VERBENA HTS BLK 04 (FSS)
Aberdeen??TOHO COURT
Tseung Kwan O??YING MING COURT BLK E MING ON HSE (HOS)
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen??YUE ON COURT BLK A (HOS)
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 04
Aberdeen??COMMAND TWR
Lam Tin??SCENEWAY GDN BLK 04
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Lam Tin??SCENEWAY GDN BLK 07
Yau Tong??LAGUNA CITY PH 01 BLK 07
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 01 TWR 3A
Tseung Kwan O??METRO CITY PH 01 TWR 02
Tseung Kwan O??CHOI MING COURT BLK B (HOS)
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen??WATERFRONT SOUTH BLK 02
Tseung Kwan O??RADIANT TWRS BLK 02 (SCHS)
Aberdeen??MARINA HABITAT BLK 01 (SCHS)
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 01 TWR 03
Aberdeen??YEN CHING BLDG
Tseung Kwan O??METRO CITY PH 02 TWR 11
Tseung Kwan O??HONG SING GDN BLK 05 (PSPS)
Aberdeen??VENG HING MAN
Aberdeen??ON TAI BLDG
Aberdeen??WATERFRONT SOUTH BLK 02
Tseung Kwan O??YU MING COURT PH 02 BLK A (HOS)
Tseung Kwan O??METRO CITY PH 01 TWR 03
Tseung Kwan O??FINERY PARK BLK 01
Yau Tong??LAGUNA CITY PH 01 BLK 06
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 05
Tseung Kwan O??KING LAM EST BLK 08 KING YUNG HSE
Tseung Kwan O??PARK CENTRAL PH 02 TWR 10
Tseung Kwan O??GRANDIOSE BLK 02
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 02
Lam Tin??SCENEWAY GDN BLK 06
Lam Tin??SCENEWAY GDN BLK 07
Yau Tong??LAGUNA CITY PH 04 BLK 19
Tseung Kwan O??METRO CITY PH 02 TWR 07
Tseung Kwan O??METRO CITY PH 02 TWR 10
Aberdeen??HUNG FOOK COURT
Tseung Kwan O??WELL ON GDN BLK 04
Yau Tong??LAGUNA CITY PH 02 BLK 29
Tseung Kwan O??METRO CITY PH 02 TWR 10
Wong Chuk Hang??GRANDVIEW GDN BLK 01
Yau Tong??LAGUNA CITY PH 03 BLK 36
Yau Tong??LAGUNA CITY PH 01 BLK 02
Tseung Kwan O??METRO CITY PH 02 TWR 02
Aberdeen??COBLE COURT
Yau Tong??LAGUNA CITY PH 03 BLK 34
Tseung Kwan O??LA CITE NOBLE BLK 03
Aberdeen??ABERDEEN CTR BLK L HOI YING COURT
Aberdeen??YUE ON COURT BLK A (HOS)
Aberdeen??ABERDEEN CTR BLK I KONG WING COURT
Yau Tong??LAGUNA CITY PH 04 BLK 22
Tseung Kwan O??HONG SING GDN BLK 04 (PSPS)
Lam Tin??SCENEWAY GDN BLK 01
Tseung Kwan O??LOHAS PARK PH 02 TWR 05 LEFT
Aberdeen??FULL JADE MAN
Yau Tong??LAGUNA CITY PH 03 BLK 32
Tseung Kwan O??VERBENA HTS BLK 03 (FSS)
Tseung Kwan O??RADIANT TWRS BLK 01 (SCHS)
Tseung Kwan O??METRO CITY PH 01 TWR 03
Aberdeen??
Tseung Kwan O??GRANDIOSE BLK 03
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 05
Lam Tin??SCENEWAY GDN BLK 07
Aberdeen??
Tseung Kwan O??METRO CITY PH 01 TWR 02
Aberdeen??
Aberdeen??
Aberdeen??
Tseung Kwan O??FINERY PARK BLK 01
Tseung Kwan O??YU MING COURT PH 01 BLK B (HOS)
Aberdeen??
Tseung Kwan O??TSUI LAM EST BLK 02 SAU LAM HSE
Lam Tin??SCENEWAY GDN BLK 12
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Yau Tong??LAGUNA CITY PH 02 BLK 27
Tseung Kwan O??METRO CITY PH 02 TWR 10
Tseung Kwan O??LOHAS PARK PH 09A MARINI TWR 03B
Lam Tin??SCENEWAY GDN BLK 07
Aberdeen??LEI TUNG EST TUNG PING HSE
Aberdeen??TIN WAN COURT
Yau Tong??LAGUNA CITY PH 01 BLK 16
Yau Tong??LAGUNA CITY PH 01 BLK 08
Aberdeen??ABERDEEN HARBOUR MANS
Yau Tong??LAGUNA CITY PH 02 BLK 29
Yau Tong??LAGUNA CITY PH 02 BLK 27
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Yau Tong??LAGUNA CITY PH 02 BLK 29
Yau Tong??LAGUNA CITY PH 01 BLK 02
Yau Tong??LAGUNA CITY PH 02 BLK 30
Yau Tong??LAGUNA CITY PH 01 BLK 16
Yau Tong??LAGUNA CITY PH 01 BLK 06
Yau Tong??LAGUNA CITY PH 01 BLK 01
Aberdeen??ON FAI BLDG
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 02 TWR 08
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 01 TWR 02
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 01 TWR 3A
Aberdeen??YEE HING BLDG
Aberdeen??YEE HING BLDG
Tseung Kwan O??HONG SING GDN BLK 03 (PSPS)
Tseung Kwan O??METRO CITY PH 02 TWR 11
Tseung Kwan O??LOHAS PARK PH 07A MONTARA TWR 02A
Yau Tong??LAGUNA CITY PH 01 BLK 07
Yau Tong??LAGUNA CITY PH 01 BLK 04
Tseung Kwan O??SERENITY PLACE BLK 02
Tseung Kwan O??KING LAM EST BLK 08 KING YUNG HSE
Yau Tong??LAGUNA CITY PH 03 BLK 33
Tseung Kwan O??PINNACLE BLK 04 (SCHS)
Tseung Kwan O??SERENITY PLACE BLK 05
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Aberdeen??KAM FUNG BLDG
Tseung Kwan O??KING LAM EST BLK 02 KING LUI HSE
Tseung Kwan O??LOHAS PARK PH 07A MONTARA TWR 02A
Tseung Kwan O??VERBENA HTS BLK 05 (FSS)
Tseung Kwan O??PO MING COURT BLK B (HOS)
Tseung Kwan O??THE WINGS IIIB TWR 01A
Tseung Kwan O??THE WINGS IIIB TWR 01A
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 04
Tseung Kwan O??BEVERLY GDN PH 02 BLK 08 (PSPS)
Tseung Kwan O??PINNACLE BLK 02 (SCHS)
Tseung Kwan O??PINNACLE BLK 04 (SCHS)
Aberdeen??TOHO COURT
Yau Tong??LAGUNA CITY PH 01 BLK 01
Aberdeen??MARINA HABITAT BLK 02 (SCHS)
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong??LAGUNA CITY PH 02 BLK 29
Yau Tong??LAGUNA CITY PH 01 BLK 05
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Tseung Kwan O??HONG SING GDN BLK 03 (PSPS)
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Yau Tong??LAGUNA CITY PH 01 BLK 07
Yau Tong??LAGUNA CITY PH 04 BLK 18
Yau Tong??LAGUNA CITY PH 01 BLK 05
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Tseung Kwan O??TSUI LAM EST BLK 06 FAI LAM HSE
Aberdeen??ABERDEEN CTR BLK M HOI TIN COURT
Aberdeen??YUE FAI COURT BLK E (HOS)
Aberdeen??SOUTH WALK AURA
Yau Tong??LAGUNA CITY PH 01 BLK 07
Aberdeen??
Aberdeen??ABBA HSE BLK B
Aberdeen??ABERDEEN CTR BLK H KONG TAI COURT
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Aberdeen??SOUTH WALK AURA
Aberdeen??ABERDEEN CTR BLK J KONG HING COURT
Tseung Kwan O??KING MING COURT BLK B FAI KING HSE (HOS)
Tseung Kwan O??METRO CITY PH 01 TWR 02
Tseung Kwan O??PO MING COURT BLK B (HOS)
Yau Tong??LAGUNA CITY PH 02 BLK 25
Yau Tong??LAGUNA CITY PH 01 BLK 07
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O??METRO CITY PH 01 TWR 01
Tseung Kwan O??PARK CENTRAL PH 02 TWR 11
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 03
Tseung Kwan O??METRO CITY PH 02 TWR 07
Yau Tong??LAGUNA CITY PH 01 BLK 02
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong??LAGUNA CITY PH 01 BLK 02
Yau Tong??LAGUNA CITY PH 02 BLK 26
Yau Tong??LAGUNA CITY PH 01 BLK 13
Yau Tong??LAGUNA CITY PH 04 BLK 18
Yau Tong??LAGUNA CITY PH 03 BLK 38
Yau Tong??LAGUNA CITY PH 04 BLK 19
Yau Tong??LAGUNA CITY PH 04 BLK 19
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Yau Tong??LAGUNA CITY PH 01 BLK 02
Yau Tong??LAGUNA CITY PH 01 BLK 07
Tseung Kwan O??SERENITY PLACE BLK 01
Aberdeen??NING FUNG MAN
Tseung Kwan O??LOHAS PARK PH 07A MONTARA TWR 02A
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O??SERENITY PLACE BLK 02
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Aberdeen??ABERDEEN CTR BLK M HOI TIN COURT
Yau Tong??LAGUNA CITY PH 04 BLK 09
Tseung Kwan O??MARITIME BAY BLK 01
Tseung Kwan O??LOHAS PARK PH 08 SEA TO SKY TWR 02
Aberdeen??KA WO BLDG BLK A
Tseung Kwan O??METRO CITY PH 02 TWR 07
Tseung Kwan O??LOHAS PARK PH 08 SEA TO SKY TWR 03
Wong Chuk Hang??GRANDVIEW GDN BLK 02
Yau Tong??LAGUNA CITY PH 02 BLK 27
Lam Tin??SCENEWAY GDN BLK 02
Yau Tong??LAGUNA CITY PH 03 BLK 33
Tseung Kwan O??OCEAN SHORES PH 03 TWR 16
Tseung Kwan O??WELL ON GDN BLK 02
Yau Tong??LAGUNA CITY PH 01 BLK 16
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 02 TWR 08
Tseung Kwan O??PARK CENTRAL PH 01 TWR 07
Tseung Kwan O??PARK CENTRAL PH 01 TWR 07
Tseung Kwan O??ON NING GDN BLK 04 (PSPS)
Aberdeen??JING HUI GDN BLK 01
Tseung Kwan O??LOHAS PARK PH 09A MARINI TWR 03A
Tseung Kwan O??METRO CITY PH 01 TWR 01
Tseung Kwan O??FINERY PARK BLK 02
Tseung Kwan O??METRO CITY PH 01 TWR 03
Aberdeen??ABERDEEN CTR BLK B HOI CHU COURT
Tseung Kwan O??KING LAM EST BLK 06 KING TAO HSE
Yau Tong??LAGUNA CITY PH 04 BLK 18
Tseung Kwan O??FINERY PARK BLK 02
Tseung Kwan O??EAST POINT CITY BLK 06
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Yau Tong??LAGUNA CITY PH 01 BLK 17
Tseung Kwan O??LA CITE NOBLE BLK 04
Tseung Kwan O??METRO CITY PH 01 TWR 04
Yau Tong??LAGUNA CITY PH 01 BLK 14
Tseung Kwan O??METRO CITY PH 02 TWR 03
Tseung Kwan O??NAN FUNG PLAZA TWR 06
Aberdeen??ABERDEEN CTR BLK M HOI TIN COURT
Aberdeen??PAT LEUNG BLDG
Yau Tong??LAGUNA CITY PH 01 BLK 02
Aberdeen??KIN FAI BLDG
Tseung Kwan O??TONG MING COURT BLK C (HOS)
Lam Tin??SCENEWAY GDN BLK 08
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 20
Tseung Kwan O??FU NING GDN BLK 03 (PSPS)
Aberdeen??KAM FUNG BLDG
Tseung Kwan O??METRO CITY PH 01 TWR 05
Aberdeen??PELENE MAN
Aberdeen??SOUTH WALK AURA
Tseung Kwan O??SERENITY PLACE BLK 02
Aberdeen??SOUTH COAST
Aberdeen??KAM FUNG BLDG
Tseung Kwan O??PO MING COURT BLK A (HOS)
Tseung Kwan O??LA CITE NOBLE BLK 05
Aberdeen??MOSBERT MAN
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Yau Tong??LAGUNA CITY PH 01 BLK 15
Tseung Kwan O??PO MING COURT BLK B (HOS)
Tseung Kwan O??HONG SING GDN BLK 03 (PSPS)
Aberdeen??YEE TIAM BLDG
Tseung Kwan O??PO MING COURT BLK B (HOS)
Aberdeen??ABERDEEN CTR BLK G KONG CHEUNG COURT
Tseung Kwan O??TWIN PEAKS TWR 02
Lam Tin??SCENEWAY GDN BLK 16
Yau Tong??LAGUNA CITY PH 02 BLK 30
Aberdeen??ABBA HSE BLK A
Tseung Kwan O??OSCAR BY THE SEA BLK 07
Tseung Kwan O??LOHAS PARK PH 07A MONTARA TWR 02B
Tseung Kwan O??NAN FUNG PLAZA TWR 06
Aberdeen??ABERDEEN HARBOUR MANS
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Aberdeen??ABERDEEN CTR BLK A HOI CHUN COURT
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 01
Yau Tong??LAGUNA CITY PH 02 BLK 24
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 20
Yau Tong??LAGUNA CITY PH 04 BLK 19
Yau Tong??LAGUNA CITY PH 04 BLK 18
Yau Tong??LAGUNA CITY PH 03 BLK 38
Yau Tong??LAGUNA CITY PH 02 BLK 30
Yau Tong??LAGUNA CITY PH 02 BLK 25
Yau Tong??LAGUNA CITY PH 01 BLK 14
Yau Tong??LAGUNA CITY PH 01 BLK 13
Yau Tong??LAGUNA CITY PH 01 BLK 02
Aberdeen??NING FUNG MAN
Aberdeen??KONG KAI BLDG
Tseung Kwan O??PARK CENTRAL PH 01 TWR 06
Tseung Kwan O??FINERY PARK BLK 02
Tseung Kwan O??TSEUNG KWAN O PLAZA PH 01 TWR 03
Tseung Kwan O??YING MING COURT BLK C MING TAT HSE (HOS)
Aberdeen??BILLION COURT
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Tseung Kwan O??PO LAM EST BLK 01 PO YAN HSE
Tseung Kwan O??KWONG MING COURT PH 01 BLK G (HOS)
Tseung Kwan O??GRANDIOSE BLK 02
Tseung Kwan O??YING MING COURT BLK A MING YUEN HSE (HOS
Tseung Kwan O??LOHAS PARK PH 02 TWR 02 LEFT
Tseung Kwan O??YU MING COURT PH 01 BLK B (HOS)
Aberdeen??PELENE MAN
Tseung Kwan O??TONG MING COURT BLK A (HOS)
Tseung Kwan O??BEVERLY GDN PH 02 BLK 05 (PSPS)
Tseung Kwan O??EAST POINT CITY BLK 02
Tseung Kwan O??YING MING COURT BLK A MING YUEN HSE (HOS
Yau Tong??LAGUNA CITY PH 02 BLK 30
Aberdeen??SOUTH WALK AURA
Aberdeen??TUNG NAM BLDG
Aberdeen??ABERDEEN CTR BLK I KONG WING COURT
Aberdeen??ABERDEEN CTR BLK E KONG FU COURT
Yau Tong??LAGUNA CITY PH 01 BLK 01
Lam Tin??SCENEWAY GDN BLK 07
Aberdeen??ABBA HSE BLK B
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Yau Tong??LAGUNA CITY PH 01 BLK 05
Yau Tong??LAGUNA CITY PH 03 BLK 32
Tseung Kwan O??KWONG MING COURT PH 01 BLK D (HOS)
Aberdeen??YUE FAI COURT BLK F (HOS)
Aberdeen??ABERDEEN CTR BLK C HOI SHAN COURT
Tseung Kwan O??YAN MING COURT BLK E (HOS)
Tseung Kwan O??WELL ON GDN BLK 04
Aberdeen??ABERDEEN CTR BLK P MEI KWONG COURT
Aberdeen??ALBERT HSE
Aberdeen??ABBA HSE BLK A
Tseung Kwan O??EAST POINT CITY BLK 05
Pokfulam??KA LUNG COURT BLK B KA PING HSE (HOS)
Tseung Kwan O??TONG MING COURT BLK B (HOS)
Tseung Kwan O??LA CITE NOBLE BLK 02
Tseung Kwan O??GRANDIOSE BLK 02
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Tseung Kwan O??KWONG MING COURT PH 01 BLK D (HOS)
Yau Tong??LAGUNA CITY PH 03 BLK 34
Tseung Kwan O??FINERY PARK BLK 01
Aberdeen??ABERDEEN CTR BLK M HOI TIN COURT
Aberdeen??YUE FAI COURT BLK C (HOS)
Tseung Kwan O??GRANDIOSE BLK 01
Tseung Kwan O??METRO CITY PH 02 TWR 02
Aberdeen??KA WO BLDG BLK A
Tseung Kwan O??LA CITE NOBLE BLK 01
Lam Tin??SCENEWAY GDN BLK 16
Yau Tong??LAGUNA CITY PH 04 BLK 18
Aberdeen??KIN FAI BLDG
Aberdeen??YUE ON COURT BLK D (HOS)
Aberdeen??COBLE COURT
Aberdeen??WAI KING MAN
Aberdeen??COMFORT CTR
Lam Tin??SCENEWAY GDN BLK 16
Tseung Kwan O??PO MING COURT BLK A (HOS)
Tseung Kwan O??KING MING COURT BLK A HEI KING HSE (HOS)
Tseung Kwan O??MARITIME BAY BLK 01
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 04
Aberdeen??COMFORT CTR
Wong Chuk Hang??GRANDVIEW GDN BLK 02
Aberdeen??COMFORT CTR
Yau Tong??LAGUNA CITY PH 04 BLK 22
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Tseung Kwan O??METRO CITY PH 02 TWR 03
Lam Tin??SCENEWAY GDN BLK 02
Yau Tong??LAGUNA CITY PH 01 BLK 04
Aberdeen??ON FAI BLDG
Yau Tong??LAGUNA CITY PH 02 BLK 27
Tseung Kwan O??METRO CITY PH 01 TWR 05
Lam Tin??SCENEWAY GDN BLK 16
Yau Tong??LAGUNA CITY PH 02 BLK 30
Yau Tong??LAGUNA CITY PH 01 BLK 06
Yau Tong??LAGUNA CITY PH 03 BLK 38
Yau Tong??LAGUNA CITY PH 01 BLK 14
Yau Tong??LAGUNA CITY PH 01 BLK 01
Tseung Kwan O??MARITIME BAY BLK 01
Yau Tong??LAGUNA CITY PH 04 BLK 11
Aberdeen??JING HUI GDN BLK 02
Aberdeen??KIN FAI BLDG
Yau Tong??LAGUNA CITY PH 03 BLK 37
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen??OCEAN HSE
Tseung Kwan O??METRO CITY PH 01 TWR 03
Lam Tin??SCENEWAY GDN BLK 06
Aberdeen??YUE FAI COURT BLK B (HOS)
Tseung Kwan O??YING MING COURT BLK C MING TAT HSE (HOS)
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 02
Aberdeen??H BONAIRE
Yau Tong??LAGUNA CITY PH 02 BLK 31
Aberdeen??LEE FAT BLDG
Yau Tong??LAGUNA CITY PH 03 BLK 33
Yau Tong??LAGUNA CITY PH 01 BLK 07
Yau Tong??LAGUNA CITY PH 01 BLK 05
Yau Tong??LAGUNA CITY PH 02 BLK 29
Yau Tong??LAGUNA CITY PH 01 BLK 05
Aberdeen??KIN FAI BLDG
Aberdeen??YUE FAI COURT BLK B (HOS)
Tseung Kwan O??HONG SING GDN BLK 05 (PSPS)
Lam Tin??SCENEWAY GDN BLK 02
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Tseung Kwan O??EAST POINT CITY BLK 02
Tseung Kwan O??BEVERLY GDN PH 01 BLK 03 (PSPS)
Aberdeen??SOUTH COAST
Aberdeen??NGAN FUNG BLDG
Aberdeen??HUNG FOOK COURT
Aberdeen??YUE FAI COURT BLK C (HOS)
Lam Tin??SCENEWAY GDN BLK 11
Yau Tong??LAGUNA CITY PH 01 BLK 04
Tseung Kwan O??METRO CITY PH 01 TWR 04
Yau Tong??LAGUNA CITY PH 02 BLK 27
Tseung Kwan O??TONG MING COURT BLK C (HOS)
Tseung Kwan O??FINERY PARK BLK 02
Aberdeen??KIN FAI BLDG
Aberdeen??ON FAI BLDG
Tseung Kwan O??METRO CITY PH 01 TWR 01
Tseung Kwan O??ALTO RESIDENCES TWR 05
Tseung Kwan O??FINERY PARK BLK 02
Tseung Kwan O??METRO CITY PH 02 TWR 07
Yau Tong??LAGUNA CITY PH 02 BLK 28
Aberdeen??HIP SING MAN
Tseung Kwan O??VERBENA HTS BLK 01 (FSS)
Aberdeen??YEN CHING BLDG
Lam Tin??SCENEWAY GDN BLK 11
Yau Tong??LAGUNA CITY PH 04 BLK 11
Aberdeen??FULL JADE MAN
Aberdeen??ABBA HSE BLK B
Aberdeen??ABERDEEN CTR BLK D HOI WU COURT
Aberdeen??ABERDEEN CTR BLK G KONG CHEUNG COURT
Aberdeen??COMFORT CTR
Yau Tong??LAGUNA CITY PH 03 BLK 34
Yau Tong??LAGUNA CITY PH 02 BLK 31
Aberdeen??YEN CHING BLDG
Tseung Kwan O??PINNACLE BLK 03 (SCHS)
Tseung Kwan O??ON NING GDN BLK 03 (PSPS)
Yau Tong??LAGUNA CITY PH 03 BLK 34
Yau Tong??LAGUNA CITY PH 01 BLK 16
Yau Tong??LAGUNA CITY PH 02 BLK 30
Tseung Kwan O??METRO CITY PH 03 THE METROPOLIS TWR 01
Tseung Kwan O??METRO TOWN PH 01 BLK 02
Yau Tong??LAGUNA CITY PH 01 BLK 05
Yau Tong??LAGUNA CITY PH 02 BLK 25
Tseung Kwan O??KWONG MING COURT PH 01 BLK C (HOS)
Tseung Kwan O??OCEAN WINGS TWR 06B
Tseung Kwan O??WELL ON GDN BLK 03
Aberdeen??SZE HEI BLDG
Aberdeen??COBLE COURT
Tseung Kwan O??GRANDIOSE BLK 02
Tseung Kwan O??RADIANT TWRS BLK 01 (SCHS)
Tseung Kwan O??METRO CITY PH 02 TWR 07
Yau Tong??LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong??LAGUNA CITY PH 01 BLK 17
Yau Tong??LAGUNA CITY PH 03 BLK 33
Aberdeen??BILLION COURT
Aberdeen??ABERDEEN CTR BLK E KONG FU COURT
Tseung Kwan O??MONTEREY TWR 01
Yau Tong??LAGUNA CITY PH 01 BLK 06
Tseung Kwan O??FINERY PARK BLK 02
Tseung Kwan O??METRO CITY PH 01 TWR 04
Aberdeen??SOUTH COAST
Yau Tong??LAGUNA CITY PH 01 BLK 16
Aberdeen??MARINA HABITAT BLK 01 (SCHS)
Aberdeen??TIN WAN COURT
Wong Chuk Hang??GRANDVIEW GDN BLK 01
Aberdeen??ABERDEEN CTR BLK A HOI CHUN COURT
Yau Tong??LAGUNA CITY PH 02 BLK 30
Yau Tong??LAGUNA CITY PH 04 BLK 22
Tseung Kwan O??GRANDIOSE BLK 01
Tseung Kwan O??METRO CITY PH 02 TWR 01
Lam Tin??SCENEWAY GDN BLK 15
Aberdeen??SOUTH COAST
Tseung Kwan O??SERENITY PLACE BLK 03
Yau Tong??LAGUNA CITY PH 04 BLK 09
Yau Tong??LAGUNA CITY PH 03 BLK 33
Tseung Kwan O??LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O??METRO CITY PH 01 TWR 01
Yau Tong??LAGUNA CITY PH 03 BLK 37
Tseung Kwan O??PO LAM EST BLK 02 PO TAI HSE
Tseung Kwan O??METRO CITY PH 01 TWR 01
Tseung Kwan O??WELL ON GDN BLK 03
Tseung Kwan O??BAUHINIA GDN TWR 03 (PSPS)
Aberdeen??ON TAI BLDG
Tseung Kwan O??METRO CITY PH 01 TWR 06
Tseung Kwan O??WELL ON GDN BLK 02
Tseung Kwan O??WELL ON GDN BLK 01
Aberdeen??YUE ON COURT BLK A (HOS)
Tseung Kwan O??EAST POINT CITY BLK 03
Aberdeen??ON TAI BLDG
Tseung Kwan O??OSCAR BY THE SEA BLK 02
Tseung Kwan O??OSCAR BY THE SEA BLK 07
Tseung Kwan O??WELL ON GDN BLK 01
Yau Tong??LAGUNA CITY PH 01 BLK 08
Yau Tong??LAGUNA CITY PH 03 BLK 37
Tseung Kwan O??METRO CITY PH 01 TWR 02
Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS)
Tseung Kwan O??THE BEAUMOUNT TWR 06
Aberdeen??JADEWATER

In [391]:
df["District1"] = df["Building / Address"].apply(lambda x: x[0:x.find("?")])
df["District2"] = df["Building / Address"].apply(lambda x: x[x.find("?")+2:])

In [393]:
for a,b in zip(df["District1"],df["District2"]):
    print(a,"----",b)

Yau Tong ----
Yau Tong ----
Yau Tong ----
Yau Tong ----
Yau Tong ----
Yau Tong ----
Yau Tong ----
Yau Tong ----
Yau Tong ----
Tseung Kwan O ---- LOHAS PARK PH 07A MONTARA TWR 02A
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 01
Tseung Kwan O ---- NAN FUNG PLAZA TWR 02
Aberdeen ---- ON TAI BLDG
Tseung Kwan O ---- METRO CITY PH 02 TWR 07
Tseung Kwan O ---- NAN FUNG PLAZA TWR 06
Tseung Kwan O ---- NAN FUNG PLAZA TWR 02
Tseung Kwan O ---- BEVERLY GDN PH 01 BLK 01 (PSPS)
Tseung Kwan O ---- THE BEAUMOUNT TWR 07
Tseung Kwan O ---- THE WINGS IIIA TWR 05A
Tseung Kwan O ---- CORINTHIA BY THE SEA TWR 02
Aberdeen ---- ABERDEEN CTR BLK I KONG WING COURT
Aberdeen ---- ALBERT HSE
Aberdeen ---- FORTUNE MAN
Yau Tong ----
Tseung Kwan O ---- CHOI MING COURT BLK E (HOS)
Tseung Kwan O ---- METRO CITY PH 02 TWR 10
Tseung Kwan O ---- METRO CITY PH 02 TWR 11
Tseung Kwan O ---- CHOI MING COURT BLK E (HOS)
Tseung Kwan O ---- FINERY PARK BLK 01
Tseung Kwan O ---- METRO CITY PH 02 TWR 10
Aberdeen ---- ABERDEEN CTR BLK B HOI CHU COURT
Aberdeen ---- KAM FAT BLDG
Aberdeen ---- MARINA HABITAT BLK 02 (SCHS)
Aberdeen ---- SOUTH COAST
Aberdeen ---- ABERDEEN CTR BLK T KWUN CHIU COURT
Yau Tong ----
Tseung Kwan O ---- THE PAPILLONS TWR 05
Tseung Kwan O ---- HIN MING COURT (HOS)
Aberdeen ---- YUE FAI COURT BLK B (HOS)
Aberdeen ---- ABERDEEN CTR BLK J KONG HING COURT
Tseung Kwan O ---- CHUNG MING COURT BLK B FAI MING HSE (HOS
Tseung Kwan O ---- TONG MING COURT BLK C (HOS)
Tseung Kwan O ---- YAN MING COURT BLK D (HOS)
Tseung Kwan O ---- PARK CENTRAL PH 02 TWR 02
Tseung Kwan O ---- OCEAN WINGS TWR 07A
Yau Tong ---- LAGUNA CITY PH 04 BLK 09
Tseung Kwan O ---- PARK CENTRAL PH 03 TWR 13
Tseung Kwan O ---- METRO CITY PH 02 TWR 05
Tseung Kwan O ---- BEVERLY GDN PH 01 BLK 03 (PSPS)
Tseung Kwan O ---- METRO CITY PH 01 TWR 02
Tseung Kwan O ---- TONG MING COURT BLK B (HOS)
Tseung Kwan O ---- KING MING COURT BLK A HEI KING HSE (HOS)
Tseung Kwan O ---- EAST POINT CITY BLK 02
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen ---- COBLE COURT
Wong Chuk Hang ---- JUMBO COURT
Tseung Kwan O ---- VERBENA HTS BLK 03 (FSS)
Tseung Kwan O ---- METRO CITY PH 02 TWR 09
Tseung Kwan O ---- VERBENA HTS BLK 05 (FSS)
Tseung Kwan O ---- PO MING COURT BLK B (HOS)
Tseung Kwan O ---- RADIANT TWRS BLK 02 (SCHS)
Yau Tong ---- LAGUNA CITY PH 03 BLK 36
Yau Tong ---- LAGUNA CITY PH 03 BLK 36
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 01 TWR 3A
Tseung Kwan O ---- ON NING GDN BLK 01 (PSPS)
Tseung Kwan O ---- GRANDIOSE BLK 03
Aberdeen ---- H BONAIRE
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 05
Aberdeen ---- YUE ON COURT BLK D (HOS)
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O ---- WELL ON GDN BLK 02
Tseung Kwan O ---- VERBENA HTS BLK 05 (FSS)
Tseung Kwan O ---- PARK CENTRAL PH 02 TWR 12
Tseung Kwan O ---- THE WINGS IIIA TWR 05A
Tseung Kwan O ---- THE WINGS TWR 03 LUNA DIAMOND
Tseung Kwan O ---- THE WINGS II TWR 05B
Yau Tong ---- LAGUNA CITY PH 02 BLK 24
Tseung Kwan O ---- VERBENA HTS BLK 04 (FSS)
Aberdeen ---- TOHO COURT
Tseung Kwan O ---- YING MING COURT BLK E MING ON HSE (HOS)
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen ---- YUE ON COURT BLK A (HOS)
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 04
Aberdeen ---- COMMAND TWR
Lam Tin ---- SCENEWAY GDN BLK 04
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Lam Tin ---- SCENEWAY GDN BLK 07
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 01 TWR 3A
Tseung Kwan O ---- METRO CITY PH 01 TWR 02
Tseung Kwan O ---- CHOI MING COURT BLK B (HOS)
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen ---- WATERFRONT SOUTH BLK 02
Tseung Kwan O ---- RADIANT TWRS BLK 02 (SCHS)
Aberdeen ---- MARINA HABITAT BLK 01 (SCHS)
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 01 TWR 03
Aberdeen ---- YEN CHING BLDG
Tseung Kwan O ---- METRO CITY PH 02 TWR 11
Tseung Kwan O ---- HONG SING GDN BLK 05 (PSPS)
Aberdeen ---- VENG HING MAN
Aberdeen ---- ON TAI BLDG
Aberdeen ---- WATERFRONT SOUTH BLK 02
Tseung Kwan O ---- YU MING COURT PH 02 BLK A (HOS)
Tseung Kwan O ---- METRO CITY PH 01 TWR 03
Tseung Kwan O ---- FINERY PARK BLK 01
Yau Tong ---- LAGUNA CITY PH 01 BLK 06
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 05
Tseung Kwan O ---- KING LAM EST BLK 08 KING YUNG HSE
Tseung Kwan O ---- PARK CENTRAL PH 02 TWR 10
Tseung Kwan O ---- GRANDIOSE BLK 02
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 02
Lam Tin ---- SCENEWAY GDN BLK 06
Lam Tin ---- SCENEWAY GDN BLK 07
Yau Tong ---- LAGUNA CITY PH 04 BLK 19
Tseung Kwan O ---- METRO CITY PH 02 TWR 07
Tseung Kwan O ---- METRO CITY PH 02 TWR 10
Aberdeen ---- HUNG FOOK COURT
Tseung Kwan O ---- WELL ON GDN BLK 04
Yau Tong ---- LAGUNA CITY PH 02 BLK 29
Tseung Kwan O ---- METRO CITY PH 02 TWR 10
Wong Chuk Hang ---- GRANDVIEW GDN BLK 01
Yau Tong ---- LAGUNA CITY PH 03 BLK 36
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Tseung Kwan O ---- METRO CITY PH 02 TWR 02
Aberdeen ---- COBLE COURT
Yau Tong ---- LAGUNA CITY PH 03 BLK 34
Tseung Kwan O ---- LA CITE NOBLE BLK 03
Aberdeen ---- ABERDEEN CTR BLK L HOI YING COURT
Aberdeen ---- YUE ON COURT BLK A (HOS)
Aberdeen ---- ABERDEEN CTR BLK I KONG WING COURT
Yau Tong ---- LAGUNA CITY PH 04 BLK 22
Tseung Kwan O ---- HONG SING GDN BLK 04 (PSPS)
Lam Tin ---- SCENEWAY GDN BLK 01
Tseung Kwan O ---- LOHAS PARK PH 02 TWR 05 LEFT
Aberdeen ---- FULL JADE MAN
Yau Tong ---- LAGUNA CITY PH 03 BLK 32
Tseung Kwan O ---- VERBENA HTS BLK 03 (FSS)
Tseung Kwan O ---- RADIANT TWRS BLK 01 (SCHS)
Tseung Kwan O ---- METRO CITY PH 01 TWR 03
Aberdeen ----
Tseung Kwan O ---- GRANDIOSE BLK 03
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 05
Lam Tin ---- SCENEWAY GDN BLK 07
Aberdeen ----
Tseung Kwan O ---- METRO CITY PH 01 TWR 02
Aberdeen ----
Aberdeen ----
Aberdeen ----
Tseung Kwan O ---- FINERY PARK BLK 01
Tseung Kwan O ---- YU MING COURT PH 01 BLK B (HOS)
Aberdeen ----
Tseung Kwan O ---- TSUI LAM EST BLK 02 SAU LAM HSE
Lam Tin ---- SCENEWAY GDN BLK 12
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Yau Tong ---- LAGUNA CITY PH 02 BLK 27
Tseung Kwan O ---- METRO CITY PH 02 TWR 10
Tseung Kwan O ---- LOHAS PARK PH 09A MARINI TWR 03B
Lam Tin ---- SCENEWAY GDN BLK 07
Aberdeen ---- LEI TUNG EST TUNG PING HSE
Aberdeen ---- TIN WAN COURT
Yau Tong ---- LAGUNA CITY PH 01 BLK 16
Yau Tong ---- LAGUNA CITY PH 01 BLK 08
Aberdeen ---- ABERDEEN HARBOUR MANS
Yau Tong ---- LAGUNA CITY PH 02 BLK 29
Yau Tong ---- LAGUNA CITY PH 02 BLK 27
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Yau Tong ---- LAGUNA CITY PH 02 BLK 29
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Yau Tong ---- LAGUNA CITY PH 02 BLK 30
Yau Tong ---- LAGUNA CITY PH 01 BLK 16
Yau Tong ---- LAGUNA CITY PH 01 BLK 06
Yau Tong ---- LAGUNA CITY PH 01 BLK 01
Aberdeen ---- ON FAI BLDG
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 02 TWR 08
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 01 TWR 02
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 01 TWR 3A
Aberdeen ---- YEE HING BLDG
Aberdeen ---- YEE HING BLDG
Tseung Kwan O ---- HONG SING GDN BLK 03 (PSPS)
Tseung Kwan O ---- METRO CITY PH 02 TWR 11
Tseung Kwan O ---- LOHAS PARK PH 07A MONTARA TWR 02A
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Yau Tong ---- LAGUNA CITY PH 01 BLK 04
Tseung Kwan O ---- SERENITY PLACE BLK 02
Tseung Kwan O ---- KING LAM EST BLK 08 KING YUNG HSE
Yau Tong ---- LAGUNA CITY PH 03 BLK 33
Tseung Kwan O ---- PINNACLE BLK 04 (SCHS)
Tseung Kwan O ---- SERENITY PLACE BLK 05
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Aberdeen ---- KAM FUNG BLDG
Tseung Kwan O ---- KING LAM EST BLK 02 KING LUI HSE
Tseung Kwan O ---- LOHAS PARK PH 07A MONTARA TWR 02A
Tseung Kwan O ---- VERBENA HTS BLK 05 (FSS)
Tseung Kwan O ---- PO MING COURT BLK B (HOS)
Tseung Kwan O ---- THE WINGS IIIB TWR 01A
Tseung Kwan O ---- THE WINGS IIIB TWR 01A
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 04
Tseung Kwan O ---- BEVERLY GDN PH 02 BLK 08 (PSPS)
Tseung Kwan O ---- PINNACLE BLK 02 (SCHS)
Tseung Kwan O ---- PINNACLE BLK 04 (SCHS)
Aberdeen ---- TOHO COURT
Yau Tong ---- LAGUNA CITY PH 01 BLK 01
Aberdeen ---- MARINA HABITAT BLK 02 (SCHS)
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong ---- LAGUNA CITY PH 02 BLK 29
Yau Tong ---- LAGUNA CITY PH 01 BLK 05
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Tseung Kwan O ---- HONG SING GDN BLK 03 (PSPS)
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Yau Tong ---- LAGUNA CITY PH 04 BLK 18
Yau Tong ---- LAGUNA CITY PH 01 BLK 05
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Tseung Kwan O ---- TSUI LAM EST BLK 06 FAI LAM HSE
Aberdeen ---- ABERDEEN CTR BLK M HOI TIN COURT
Aberdeen ---- YUE FAI COURT BLK E (HOS)
Aberdeen ---- SOUTH WALK AURA
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Aberdeen ----
Aberdeen ---- ABBA HSE BLK B
Aberdeen ---- ABERDEEN CTR BLK H KONG TAI COURT
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Aberdeen ---- SOUTH WALK AURA
Aberdeen ---- ABERDEEN CTR BLK J KONG HING COURT
Tseung Kwan O ---- KING MING COURT BLK B FAI KING HSE (HOS)
Tseung Kwan O ---- METRO CITY PH 01 TWR 02
Tseung Kwan O ---- PO MING COURT BLK B (HOS)
Yau Tong ---- LAGUNA CITY PH 02 BLK 25
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O ---- METRO CITY PH 01 TWR 01
Tseung Kwan O ---- PARK CENTRAL PH 02 TWR 11
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 03
Tseung Kwan O ---- METRO CITY PH 02 TWR 07
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Yau Tong ---- LAGUNA CITY PH 02 BLK 26
Yau Tong ---- LAGUNA CITY PH 01 BLK 13
Yau Tong ---- LAGUNA CITY PH 04 BLK 18
Yau Tong ---- LAGUNA CITY PH 03 BLK 38
Yau Tong ---- LAGUNA CITY PH 04 BLK 19
Yau Tong ---- LAGUNA CITY PH 04 BLK 19
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Tseung Kwan O ---- SERENITY PLACE BLK 01
Aberdeen ---- NING FUNG MAN
Tseung Kwan O ---- LOHAS PARK PH 07A MONTARA TWR 02A
Tseung Kwan O ---- LOHAS PARK PH 06 LP6 TWR 03
Tseung Kwan O ---- SERENITY PLACE BLK 02
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Aberdeen ---- ABERDEEN CTR BLK M HOI TIN COURT
Yau Tong ---- LAGUNA CITY PH 04 BLK 09
Tseung Kwan O ---- MARITIME BAY BLK 01
Tseung Kwan O ---- LOHAS PARK PH 08 SEA TO SKY TWR 02
Aberdeen ---- KA WO BLDG BLK A
Tseung Kwan O ---- METRO CITY PH 02 TWR 07
Tseung Kwan O ---- LOHAS PARK PH 08 SEA TO SKY TWR 03
Wong Chuk Hang ---- GRANDVIEW GDN BLK 02
Yau Tong ---- LAGUNA CITY PH 02 BLK 27
Lam Tin ---- SCENEWAY GDN BLK 02
Yau Tong ---- LAGUNA CITY PH 03 BLK 33
Tseung Kwan O ---- OCEAN SHORES PH 03 TWR 16
Tseung Kwan O ---- WELL ON GDN BLK 02
Yau Tong ---- LAGUNA CITY PH 01 BLK 16
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 02 TWR 08
Tseung Kwan O ---- PARK CENTRAL PH 01 TWR 07
Tseung Kwan O ---- PARK CENTRAL PH 01 TWR 07
Tseung Kwan O ---- ON NING GDN BLK 04 (PSPS)
Aberdeen ---- JING HUI GDN BLK 01
Tseung Kwan O ---- LOHAS PARK PH 09A MARINI TWR 03A
Tseung Kwan O ---- METRO CITY PH 01 TWR 01
Tseung Kwan O ---- FINERY PARK BLK 02
Tseung Kwan O ---- METRO CITY PH 01 TWR 03
Aberdeen ---- ABERDEEN CTR BLK B HOI CHU COURT
Tseung Kwan O ---- KING LAM EST BLK 06 KING TAO HSE
Yau Tong ---- LAGUNA CITY PH 04 BLK 18
Tseung Kwan O ---- FINERY PARK BLK 02
Tseung Kwan O ---- EAST POINT CITY BLK 06
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Yau Tong ---- LAGUNA CITY PH 01 BLK 17
Tseung Kwan O ---- LA CITE NOBLE BLK 04
Tseung Kwan O ---- METRO CITY PH 01 TWR 04
Yau Tong ---- LAGUNA CITY PH 01 BLK 14
Tseung Kwan O ---- METRO CITY PH 02 TWR 03
Tseung Kwan O ---- NAN FUNG PLAZA TWR 06
Aberdeen ---- ABERDEEN CTR BLK M HOI TIN COURT
Aberdeen ---- PAT LEUNG BLDG
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Aberdeen ---- KIN FAI BLDG
Tseung Kwan O ---- TONG MING COURT BLK C (HOS)
Lam Tin ---- SCENEWAY GDN BLK 08
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 20
Tseung Kwan O ---- FU NING GDN BLK 03 (PSPS)
Aberdeen ---- KAM FUNG BLDG
Tseung Kwan O ---- METRO CITY PH 01 TWR 05
Aberdeen ---- PELENE MAN
Aberdeen ---- SOUTH WALK AURA
Tseung Kwan O ---- SERENITY PLACE BLK 02
Aberdeen ---- SOUTH COAST
Aberdeen ---- KAM FUNG BLDG
Tseung Kwan O ---- PO MING COURT BLK A (HOS)
Tseung Kwan O ---- LA CITE NOBLE BLK 05
Aberdeen ---- MOSBERT MAN
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Yau Tong ---- LAGUNA CITY PH 01 BLK 15
Tseung Kwan O ---- PO MING COURT BLK B (HOS)
Tseung Kwan O ---- HONG SING GDN BLK 03 (PSPS)
Aberdeen ---- YEE TIAM BLDG
Tseung Kwan O ---- PO MING COURT BLK B (HOS)
Aberdeen ---- ABERDEEN CTR BLK G KONG CHEUNG COURT
Tseung Kwan O ---- TWIN PEAKS TWR 02
Lam Tin ---- SCENEWAY GDN BLK 16
Yau Tong ---- LAGUNA CITY PH 02 BLK 30
Aberdeen ---- ABBA HSE BLK A
Tseung Kwan O ---- OSCAR BY THE SEA BLK 07
Tseung Kwan O ---- LOHAS PARK PH 07A MONTARA TWR 02B
Tseung Kwan O ---- NAN FUNG PLAZA TWR 06
Aberdeen ---- ABERDEEN HARBOUR MANS
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 10
Aberdeen ---- ABERDEEN CTR BLK A HOI CHUN COURT
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 01
Yau Tong ---- LAGUNA CITY PH 02 BLK 24
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 20
Yau Tong ---- LAGUNA CITY PH 04 BLK 19
Yau Tong ---- LAGUNA CITY PH 04 BLK 18
Yau Tong ---- LAGUNA CITY PH 03 BLK 38
Yau Tong ---- LAGUNA CITY PH 02 BLK 30
Yau Tong ---- LAGUNA CITY PH 02 BLK 25
Yau Tong ---- LAGUNA CITY PH 01 BLK 14
Yau Tong ---- LAGUNA CITY PH 01 BLK 13
Yau Tong ---- LAGUNA CITY PH 01 BLK 02
Aberdeen ---- NING FUNG MAN
Aberdeen ---- KONG KAI BLDG
Tseung Kwan O ---- PARK CENTRAL PH 01 TWR 06
Tseung Kwan O ---- FINERY PARK BLK 02
Tseung Kwan O ---- TSEUNG KWAN O PLAZA PH 01 TWR 03
Tseung Kwan O ---- YING MING COURT BLK C MING TAT HSE (HOS)
Aberdeen ---- BILLION COURT
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Tseung Kwan O ---- PO LAM EST BLK 01 PO YAN HSE
Tseung Kwan O ---- KWONG MING COURT PH 01 BLK G (HOS)
Tseung Kwan O ---- GRANDIOSE BLK 02
Tseung Kwan O ---- YING MING COURT BLK A MING YUEN HSE (HOS
Tseung Kwan O ---- LOHAS PARK PH 02 TWR 02 LEFT
Tseung Kwan O ---- YU MING COURT PH 01 BLK B (HOS)
Aberdeen ---- PELENE MAN
Tseung Kwan O ---- TONG MING COURT BLK A (HOS)
Tseung Kwan O ---- BEVERLY GDN PH 02 BLK 05 (PSPS)
Tseung Kwan O ---- EAST POINT CITY BLK 02
Tseung Kwan O ---- YING MING COURT BLK A MING YUEN HSE (HOS
Yau Tong ---- LAGUNA CITY PH 02 BLK 30
Aberdeen ---- SOUTH WALK AURA
Aberdeen ---- TUNG NAM BLDG
Aberdeen ---- ABERDEEN CTR BLK I KONG WING COURT
Aberdeen ---- ABERDEEN CTR BLK E KONG FU COURT
Yau Tong ---- LAGUNA CITY PH 01 BLK 01
Lam Tin ---- SCENEWAY GDN BLK 07
Aberdeen ---- ABBA HSE BLK B
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 23
Yau Tong ---- LAGUNA CITY PH 01 BLK 05
Yau Tong ---- LAGUNA CITY PH 03 BLK 32
Tseung Kwan O ---- KWONG MING COURT PH 01 BLK D (HOS)
Aberdeen ---- YUE FAI COURT BLK F (HOS)
Aberdeen ---- ABERDEEN CTR BLK C HOI SHAN COURT
Tseung Kwan O ---- YAN MING COURT BLK E (HOS)
Tseung Kwan O ---- WELL ON GDN BLK 04
Aberdeen ---- ABERDEEN CTR BLK P MEI KWONG COURT
Aberdeen ---- ALBERT HSE
Aberdeen ---- ABBA HSE BLK A
Tseung Kwan O ---- EAST POINT CITY BLK 05
Pokfulam ---- KA LUNG COURT BLK B KA PING HSE (HOS)
Tseung Kwan O ---- TONG MING COURT BLK B (HOS)
Tseung Kwan O ---- LA CITE NOBLE BLK 02
Tseung Kwan O ---- GRANDIOSE BLK 02
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Tseung Kwan O ---- KWONG MING COURT PH 01 BLK D (HOS)
Yau Tong ---- LAGUNA CITY PH 03 BLK 34
Tseung Kwan O ---- FINERY PARK BLK 01
Aberdeen ---- ABERDEEN CTR BLK M HOI TIN COURT
Aberdeen ---- YUE FAI COURT BLK C (HOS)
Tseung Kwan O ---- GRANDIOSE BLK 01
Tseung Kwan O ---- METRO CITY PH 02 TWR 02
Aberdeen ---- KA WO BLDG BLK A
Tseung Kwan O ---- LA CITE NOBLE BLK 01
Lam Tin ---- SCENEWAY GDN BLK 16
Yau Tong ---- LAGUNA CITY PH 04 BLK 18
Aberdeen ---- KIN FAI BLDG
Aberdeen ---- YUE ON COURT BLK D (HOS)
Aberdeen ---- COBLE COURT
Aberdeen ---- WAI KING MAN
Aberdeen ---- COMFORT CTR
Lam Tin ---- SCENEWAY GDN BLK 16
Tseung Kwan O ---- PO MING COURT BLK A (HOS)
Tseung Kwan O ---- KING MING COURT BLK A HEI KING HSE (HOS)
Tseung Kwan O ---- MARITIME BAY BLK 01
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 04
Aberdeen ---- COMFORT CTR
Wong Chuk Hang ---- GRANDVIEW GDN BLK 02
Aberdeen ---- COMFORT CTR
Yau Tong ---- LAGUNA CITY PH 04 BLK 22
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Tseung Kwan O ---- METRO CITY PH 02 TWR 03
Lam Tin ---- SCENEWAY GDN BLK 02
Yau Tong ---- LAGUNA CITY PH 01 BLK 04
Aberdeen ---- ON FAI BLDG
Yau Tong ---- LAGUNA CITY PH 02 BLK 27
Tseung Kwan O ---- METRO CITY PH 01 TWR 05
Lam Tin ---- SCENEWAY GDN BLK 16
Yau Tong ---- LAGUNA CITY PH 02 BLK 30
Yau Tong ---- LAGUNA CITY PH 01 BLK 06
Yau Tong ---- LAGUNA CITY PH 03 BLK 38
Yau Tong ---- LAGUNA CITY PH 01 BLK 14
Yau Tong ---- LAGUNA CITY PH 01 BLK 01
Tseung Kwan O ---- MARITIME BAY BLK 01
Yau Tong ---- LAGUNA CITY PH 04 BLK 11
Aberdeen ---- JING HUI GDN BLK 02
Aberdeen ---- KIN FAI BLDG
Yau Tong ---- LAGUNA CITY PH 03 BLK 37
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 01
Aberdeen ---- OCEAN HSE
Tseung Kwan O ---- METRO CITY PH 01 TWR 03
Lam Tin ---- SCENEWAY GDN BLK 06
Aberdeen ---- YUE FAI COURT BLK B (HOS)
Tseung Kwan O ---- YING MING COURT BLK C MING TAT HSE (HOS)
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 02
Aberdeen ---- H BONAIRE
Yau Tong ---- LAGUNA CITY PH 02 BLK 31
Aberdeen ---- LEE FAT BLDG
Yau Tong ---- LAGUNA CITY PH 03 BLK 33
Yau Tong ---- LAGUNA CITY PH 01 BLK 07
Yau Tong ---- LAGUNA CITY PH 01 BLK 05
Yau Tong ---- LAGUNA CITY PH 02 BLK 29
Yau Tong ---- LAGUNA CITY PH 01 BLK 05
Aberdeen ---- KIN FAI BLDG
Aberdeen ---- YUE FAI COURT BLK B (HOS)
Tseung Kwan O ---- HONG SING GDN BLK 05 (PSPS)
Lam Tin ---- SCENEWAY GDN BLK 02
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 12
Tseung Kwan O ---- EAST POINT CITY BLK 02
Tseung Kwan O ---- BEVERLY GDN PH 01 BLK 03 (PSPS)
Aberdeen ---- SOUTH COAST
Aberdeen ---- NGAN FUNG BLDG
Aberdeen ---- HUNG FOOK COURT
Aberdeen ---- YUE FAI COURT BLK C (HOS)
Lam Tin ---- SCENEWAY GDN BLK 11
Yau Tong ---- LAGUNA CITY PH 01 BLK 04
Tseung Kwan O ---- METRO CITY PH 01 TWR 04
Yau Tong ---- LAGUNA CITY PH 02 BLK 27
Tseung Kwan O ---- TONG MING COURT BLK C (HOS)
Tseung Kwan O ---- FINERY PARK BLK 02
Aberdeen ---- KIN FAI BLDG
Aberdeen ---- ON FAI BLDG
Tseung Kwan O ---- METRO CITY PH 01 TWR 01
Tseung Kwan O ---- ALTO RESIDENCES TWR 05
Tseung Kwan O ---- FINERY PARK BLK 02
Tseung Kwan O ---- METRO CITY PH 02 TWR 07
Yau Tong ---- LAGUNA CITY PH 02 BLK 28
Aberdeen ---- HIP SING MAN
Tseung Kwan O ---- VERBENA HTS BLK 01 (FSS)
Aberdeen ---- YEN CHING BLDG
Lam Tin ---- SCENEWAY GDN BLK 11
Yau Tong ---- LAGUNA CITY PH 04 BLK 11
Aberdeen ---- FULL JADE MAN
Aberdeen ---- ABBA HSE BLK B
Aberdeen ---- ABERDEEN CTR BLK D HOI WU COURT
Aberdeen ---- ABERDEEN CTR BLK G KONG CHEUNG COURT
Aberdeen ---- COMFORT CTR
Yau Tong ---- LAGUNA CITY PH 03 BLK 34
Yau Tong ---- LAGUNA CITY PH 02 BLK 31
Aberdeen ---- YEN CHING BLDG
Tseung Kwan O ---- PINNACLE BLK 03 (SCHS)
Tseung Kwan O ---- ON NING GDN BLK 03 (PSPS)
Yau Tong ---- LAGUNA CITY PH 03 BLK 34
Yau Tong ---- LAGUNA CITY PH 01 BLK 16
Yau Tong ---- LAGUNA CITY PH 02 BLK 30
Tseung Kwan O ---- METRO CITY PH 03 THE METROPOLIS TWR 01
Tseung Kwan O ---- METRO TOWN PH 01 BLK 02
Yau Tong ---- LAGUNA CITY PH 01 BLK 05
Yau Tong ---- LAGUNA CITY PH 02 BLK 25
Tseung Kwan O ---- KWONG MING COURT PH 01 BLK C (HOS)
Tseung Kwan O ---- OCEAN WINGS TWR 06B
Tseung Kwan O ---- WELL ON GDN BLK 03
Aberdeen ---- SZE HEI BLDG
Aberdeen ---- COBLE COURT
Tseung Kwan O ---- GRANDIOSE BLK 02
Tseung Kwan O ---- RADIANT TWRS BLK 01 (SCHS)
Tseung Kwan O ---- METRO CITY PH 02 TWR 07
Yau Tong ---- LAGUNA CITY PH 04 LAGUNA COVE BLK 21
Yau Tong ---- LAGUNA CITY PH 01 BLK 17
Yau Tong ---- LAGUNA CITY PH 03 BLK 33
Aberdeen ---- BILLION COURT
Aberdeen ---- ABERDEEN CTR BLK E KONG FU COURT

In [394]:
import statistics

In [395]:
f = [int(i) for i in df["Floor"] if i.isdigit()]

f.sort()
print(f)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 26, 27, 27, 27, 28, 32, 32]

In [396]:
test_f = pd.DataFrame(f)
test_f.describe()

                0
count  167.000000
mean    13.083832
std      8.343104
min      1.000000
25%      5.500000
50%     13.000000
75%     21.000000
max     32.000000

In [397]:
for i in df.Floor:
    print(i, type(i))

23 <class 'str'>
18 <class 'str'>
25 <class 'str'>
22 <class 'str'>
7 <class 'str'>
6 <class 'str'>
10 <class 'str'>
23 <class 'str'>
20 <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
L <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
2 <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
?????? <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
6 <class 'str'>
L <class 'str'>
H <class 'str'>
L <class 'str'>
L <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
1 <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
20 <class 'str'>
6 <class 'str'>
L <class 'str'>
M <class 'str'>
M <class 'str'>
M <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
24 <class 'str'>
H <class 'str'>
?????? <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
24 <class 'str'>
2 <class 'str'>
14 <class 'str'>
1 <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
M <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
6 <class 'str'>
6 <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
23 <class 'str'>
5 <class 'str'>
9 <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
13 <class 'str'>
L <class 'str'>
H <class 'str'>
12 <class 'str'>
5 <class 'str'>
M <class 'str'>
H <class 'str'>
4 <class 'str'>
L <class 'str'>
H <class 'str'>
?????? <class 'str'>
L <class 'str'>
2 <class 'str'>
M <class 'str'>
16 <class 'str'>
H <class 'str'>
H <class 'str'>
2 <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
27 <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
M <class 'str'>
?????? <class 'str'>
M <class 'str'>
25 <class 'str'>
1 <class 'str'>
4 <class 'str'>
H <class 'str'>
L <class 'str'>
32 <class 'str'>
H <class 'str'>
L <class 'str'>
12 <class 'str'>
22 <class 'str'>
H <class 'str'>
23 <class 'str'>
6 <class 'str'>
3 <class 'str'>
17 <class 'str'>
22 <class 'str'>
22 <class 'str'>
16 <class 'str'>
13 <class 'str'>
25 <class 'str'>
1 <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
1 <class 'str'>
19 <class 'str'>
H <class 'str'>
H <class 'str'>
6 <class 'str'>
H <class 'str'>
M <class 'str'>
5 <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
L <class 'str'>
L <class 'str'>
L <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
27 <class 'str'>
H <class 'str'>
6 <class 'str'>
13 <class 'str'>
22 <class 'str'>
23 <class 'str'>
L <class 'str'>
5 <class 'str'>
1 <class 'str'>
24 <class 'str'>
26 <class 'str'>
17 <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
10 <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
4 <class 'str'>
?????? <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
6 <class 'str'>
12 <class 'str'>
H <class 'str'>
L <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
12 <class 'str'>
2 <class 'str'>
3 <class 'str'>
20 <class 'str'>
20 <class 'str'>
16 <class 'str'>
21 <class 'str'>
23 <class 'str'>
21 <class 'str'>
9 <class 'str'>
22 <class 'str'>
2 <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
5 <class 'str'>
H <class 'str'>
16 <class 'str'>
L <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
1 <class 'str'>
14 <class 'str'>
19 <class 'str'>
H <class 'str'>
M <class 'str'>
17 <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
L <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
1 <class 'str'>
H <class 'str'>
H <class 'str'>
10 <class 'str'>
18 <class 'str'>
H <class 'str'>
M <class 'str'>
12 <class 'str'>
L <class 'str'>
M <class 'str'>
H <class 'str'>
L <class 'str'>
10 <class 'str'>
L <class 'str'>
H <class 'str'>
20 <class 'str'>
7 <class 'str'>
M <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
?????? <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
16 <class 'str'>
2 <class 'str'>
M <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
L <class 'str'>
22 <class 'str'>
1 <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
16 <class 'str'>
H <class 'str'>
M <class 'str'>
11 <class 'str'>
19 <class 'str'>
18 <class 'str'>
22 <class 'str'>
1 <class 'str'>
25 <class 'str'>
24 <class 'str'>
14 <class 'str'>
5 <class 'str'>
14 <class 'str'>
23 <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
21 <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
L <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
L <class 'str'>
2 <class 'str'>
M <class 'str'>
H <class 'str'>
?????? <class 'str'>
H <class 'str'>
1 <class 'str'>
6 <class 'str'>
H <class 'str'>
8 <class 'str'>
2 <class 'str'>
23 <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
1 <class 'str'>
H <class 'str'>
4 <class 'str'>
H <class 'str'>
L <class 'str'>
?????? <class 'str'>
H <class 'str'>
L <class 'str'>
L <class 'str'>
H <class 'str'>
11 <class 'str'>
4 <class 'str'>
L <class 'str'>
L <class 'str'>
L <class 'str'>
?????? <class 'str'>
H <class 'str'>
8 <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
15 <class 'str'>
17 <class 'str'>
M <class 'str'>
17 <class 'str'>
25 <class 'str'>
L <class 'str'>
10 <class 'str'>
H <class 'str'>
20 <class 'str'>
5 <class 'str'>
3 <class 'str'>
21 <class 'str'>
14 <class 'str'>
10 <class 'str'>
L <class 'str'>
10 <class 'str'>
H <class 'str'>
H <class 'str'>
4 <class 'str'>
H <class 'str'>
?????? <class 'str'>
H <class 'str'>
32 <class 'str'>
?????? <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
20 <class 'str'>
H <class 'str'>
10 <class 'str'>
17 <class 'str'>
11 <class 'str'>
3 <class 'str'>
7 <class 'str'>
M <class 'str'>
L <class 'str'>
M <class 'str'>
8 <class 'str'>
5 <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
28 <class 'str'>
24 <class 'str'>
H <class 'str'>
21 <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
M <class 'str'>
7 <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
22 <class 'str'>
15 <class 'str'>
M <class 'str'>
?????? <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
25 <class 'str'>
15 <class 'str'>
L <class 'str'>
L <class 'str'>
H <class 'str'>
27 <class 'str'>
15 <class 'str'>
15 <class 'str'>
M <class 'str'>
H <class 'str'>
4 <class 'str'>
25 <class 'str'>
M <class 'str'>
L <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
8 <class 'str'>
8 <class 'str'>
10 <class 'str'>
H <class 'str'>
H <class 'str'>
L <class 'str'>
8 <class 'str'>
M <class 'str'>
L <class 'str'>
H <class 'str'>
3 <class 'str'>
H <class 'str'>
L <class 'str'>
L <class 'str'>
H <class 'str'>
24 <class 'str'>
25 <class 'str'>
H <class 'str'>
M <class 'str'>
3 <class 'str'>
H <class 'str'>
H <class 'str'>
13 <class 'str'>
16 <class 'str'>
H <class 'str'>
L <class 'str'>
12 <class 'str'>
L <class 'str'>
H <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
M <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
H <class 'str'>
13 <class 'str'>
15 <class 'str'>
H <class 'str'>
L <class 'str'>
H <class 'str'>
?????? <class 'str'>

In [398]:
l,m,h = (1,int(max(f)/3)),(int(max(f)/3)+1,int(max(f)*(2/3))),(int(max(f)*(2/3))+1,max(f))
print(l,m,h)

(1, 10) (11, 21) (22, 32)

In [399]:
df["Floor"]

0          23
1          18
2          25
3          22
4           7
        ...
550        15
552         H
553         L
554         H
555    ??????
Name: Floor, Length: 539, dtype: object

In [400]:
def floor_change(x):
    if x.isdigit() and int(x) >= l[0] and int(x) <= l[1]:
        return "L"
    elif x.isdigit() and int(x) >= m[0] and int(x) <= m[1]:
        return "M"
    elif x.isdigit() and int(x) >= h[0] and int(x) <= h[1]:
        return "H"
    else:
        return "Others"

In [401]:
df["Floor"] = df["Floor"].apply(lambda x: floor_change(x))

In [402]:
df

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA),District1,District2
0,2022-04-30,Yau Tong??,H,687,"20,000",@29,Yau Tong,
1,2022-04-30,Yau Tong??,M,517,"15,000",@29,Yau Tong,
2,2022-04-30,Yau Tong??,H,748,"21,500",@29,Yau Tong,
3,2022-04-30,Yau Tong??,H,748,"20,500",@27,Yau Tong,
4,2022-04-30,Yau Tong??,L,522,"16,500",@32,Yau Tong,
...,...,...,...,...,...,...,...,...
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,M,517,"16,300",@32,Yau Tong,LAGUNA CITY PH 03 BLK 37
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,Others,364,"15,000",@41,Tseung Kwan O,METRO CITY PH 01 TWR 02
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),Others,484,"14,500",@30,Tseung Kwan O,BEVERLY GDN PH 02 BLK 09 (PSPS)
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,Others,501,"15,500",@31,Tseung Kwan O,THE BEAUMOUNT TWR 06
555,2021-10-05,Aberdeen??JADEWATER ...,Others,519,"21,000",@40,Aberdeen,JADEWATER

In [403]:
df

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA),District1,District2
0,2022-04-30,Yau Tong??,H,687,"20,000",@29,Yau Tong,
1,2022-04-30,Yau Tong??,M,517,"15,000",@29,Yau Tong,
2,2022-04-30,Yau Tong??,H,748,"21,500",@29,Yau Tong,
3,2022-04-30,Yau Tong??,H,748,"20,500",@27,Yau Tong,
4,2022-04-30,Yau Tong??,L,522,"16,500",@32,Yau Tong,
...,...,...,...,...,...,...,...,...
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,M,517,"16,300",@32,Yau Tong,LAGUNA CITY PH 03 BLK 37
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,Others,364,"15,000",@41,Tseung Kwan O,METRO CITY PH 01 TWR 02
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),Others,484,"14,500",@30,Tseung Kwan O,BEVERLY GDN PH 02 BLK 09 (PSPS)
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,Others,501,"15,500",@31,Tseung Kwan O,THE BEAUMOUNT TWR 06
555,2021-10-05,Aberdeen??JADEWATER ...,Others,519,"21,000",@40,Aberdeen,JADEWATER

In [404]:
df["SA (ft2)"] = df["SA (ft2)"].str.replace(r'\D', '')
df["Price(HK$)"] = df["Price(HK$)"].str.replace(r'\D', '')

df

C:\Users\Benny\AppData\Local\Temp/ipykernel_98184/552305841.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["SA (ft2)"] = df["SA (ft2)"].str.replace(r'\D', '')
C:\Users\Benny\AppData\Local\Temp/ipykernel_98184/552305841.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Price(HK$)"] = df["Price(HK$)"].str.replace(r'\D', '')

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA),District1,District2
0,2022-04-30,Yau Tong??,H,687,20000,@29,Yau Tong,
1,2022-04-30,Yau Tong??,M,517,15000,@29,Yau Tong,
2,2022-04-30,Yau Tong??,H,748,21500,@29,Yau Tong,
3,2022-04-30,Yau Tong??,H,748,20500,@27,Yau Tong,
4,2022-04-30,Yau Tong??,L,522,16500,@32,Yau Tong,
...,...,...,...,...,...,...,...,...
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,M,517,16300,@32,Yau Tong,LAGUNA CITY PH 03 BLK 37
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,Others,364,15000,@41,Tseung Kwan O,METRO CITY PH 01 TWR 02
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),Others,484,14500,@30,Tseung Kwan O,BEVERLY GDN PH 02 BLK 09 (PSPS)
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,Others,501,15500,@31,Tseung Kwan O,THE BEAUMOUNT TWR 06
555,2021-10-05,Aberdeen??JADEWATER ...,Others,519,21000,@40,Aberdeen,JADEWATER

In [405]:

df["SA (ft2)"] = df["SA (ft2)"].astype(int)
df["Price(HK$)"] = df["Price(HK$)"].astype(int)
df["Price/ft2(SA)"] = df["Price(HK$)"]/df["SA (ft2)"]

df

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA),District1,District2
0,2022-04-30,Yau Tong??,H,687,20000,29.112082,Yau Tong,
1,2022-04-30,Yau Tong??,M,517,15000,29.013540,Yau Tong,
2,2022-04-30,Yau Tong??,H,748,21500,28.743316,Yau Tong,
3,2022-04-30,Yau Tong??,H,748,20500,27.406417,Yau Tong,
4,2022-04-30,Yau Tong??,L,522,16500,31.609195,Yau Tong,
...,...,...,...,...,...,...,...,...
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,M,517,16300,31.528046,Yau Tong,LAGUNA CITY PH 03 BLK 37
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,Others,364,15000,41.208791,Tseung Kwan O,METRO CITY PH 01 TWR 02
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),Others,484,14500,29.958678,Tseung Kwan O,BEVERLY GDN PH 02 BLK 09 (PSPS)
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,Others,501,15500,30.938124,Tseung Kwan O,THE BEAUMOUNT TWR 06
555,2021-10-05,Aberdeen??JADEWATER ...,Others,519,21000,40.462428,Aberdeen,JADEWATER

In [406]:
df = df.round({'Price/ft2(SA)': 2})
df

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA),District1,District2
0,2022-04-30,Yau Tong??,H,687,20000,29.11,Yau Tong,
1,2022-04-30,Yau Tong??,M,517,15000,29.01,Yau Tong,
2,2022-04-30,Yau Tong??,H,748,21500,28.74,Yau Tong,
3,2022-04-30,Yau Tong??,H,748,20500,27.41,Yau Tong,
4,2022-04-30,Yau Tong??,L,522,16500,31.61,Yau Tong,
...,...,...,...,...,...,...,...,...
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,M,517,16300,31.53,Yau Tong,LAGUNA CITY PH 03 BLK 37
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,Others,364,15000,41.21,Tseung Kwan O,METRO CITY PH 01 TWR 02
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),Others,484,14500,29.96,Tseung Kwan O,BEVERLY GDN PH 02 BLK 09 (PSPS)
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,Others,501,15500,30.94,Tseung Kwan O,THE BEAUMOUNT TWR 06
555,2021-10-05,Aberdeen??JADEWATER ...,Others,519,21000,40.46,Aberdeen,JADEWATER

In [407]:
df = df.sort_values(by="Date")
df

,Date,Building / Address,Floor,SA (ft2),Price(HK$),Price/ft2(SA),District1,District2
555,2021-10-05,Aberdeen??JADEWATER ...,Others,519,21000,40.46,Aberdeen,JADEWATER
552,2021-10-05,Tseung Kwan O??METRO CITY PH 01 TWR 02,Others,364,15000,41.21,Tseung Kwan O,METRO CITY PH 01 TWR 02
554,2021-10-05,Tseung Kwan O??THE BEAUMOUNT TWR 06,Others,501,15500,30.94,Tseung Kwan O,THE BEAUMOUNT TWR 06
553,2021-10-05,Tseung Kwan O??BEVERLY GDN PH 02 BLK 09 (PSPS),Others,484,14500,29.96,Tseung Kwan O,BEVERLY GDN PH 02 BLK 09 (PSPS)
550,2021-10-06,Yau Tong??LAGUNA CITY PH 03 BLK 37 ...,M,517,16300,31.53,Yau Tong,LAGUNA CITY PH 03 BLK 37
...,...,...,...,...,...,...,...,...
4,2022-04-30,Yau Tong??,L,522,16500,31.61,Yau Tong,
3,2022-04-30,Yau Tong??,H,748,20500,27.41,Yau Tong,
2,2022-04-30,Yau Tong??,H,748,21500,28.74,Yau Tong,
1,2022-04-30,Yau Tong??,M,517,15000,29.01,Yau Tong,
0,2022-04-30,Yau Tong??,H,687,20000,29.11,Yau Tong,

In [409]:
for i in df.District2:
    print(i)

JADEWATER
METRO CITY PH 01 TWR 02
THE BEAUMOUNT TWR 06
BEVERLY GDN PH 02 BLK 09 (PSPS)
LAGUNA CITY PH 03 BLK 37
LAGUNA CITY PH 01 BLK 08
WELL ON GDN BLK 01
OSCAR BY THE SEA BLK 07
OSCAR BY THE SEA BLK 02
ON TAI BLDG
EAST POINT CITY BLK 03
YUE ON COURT BLK A (HOS)
WELL ON GDN BLK 01
WELL ON GDN BLK 02
METRO CITY PH 01 TWR 06
ON TAI BLDG
BAUHINIA GDN TWR 03 (PSPS)
WELL ON GDN BLK 03
METRO CITY PH 01 TWR 01
PO LAM EST BLK 02 PO TAI HSE
LAGUNA CITY PH 03 BLK 37
LOHAS PARK PH 06 LP6 TWR 03
METRO CITY PH 01 TWR 01
LAGUNA CITY PH 03 BLK 33
LAGUNA CITY PH 04 BLK 09
SERENITY PLACE BLK 03
SOUTH COAST
SCENEWAY GDN BLK 15
METRO CITY PH 02 TWR 01
GRANDIOSE BLK 01
LAGUNA CITY PH 04 BLK 22
LAGUNA CITY PH 02 BLK 30
ABERDEEN CTR BLK A HOI CHUN COURT
GRANDVIEW GDN BLK 01
TIN WAN COURT
MARINA HABITAT BLK 01 (SCHS)
LAGUNA CITY PH 01 BLK 16
LAGUNA CITY PH 01 BLK 06
SOUTH COAST
METRO CITY PH 01 TWR 04
FINERY PARK BLK 02
MONTEREY TWR 01
ABERDEEN CTR BLK E KONG FU COURT
BILLION COURT
LAGUNA CITY PH 03 BLK 33
LAGUNA CITY PH 01 BLK 17
LAGUNA CITY PH 04 LAGUNA COVE BLK 21
METRO CITY PH 02 TWR 07
RADIANT TWRS BLK 01 (SCHS)
GRANDIOSE BLK 02
COBLE COURT
SZE HEI BLDG
WELL ON GDN BLK 03
LAGUNA CITY PH 01 BLK 05
KWONG MING COURT PH 01 BLK C (HOS)
OCEAN WINGS TWR 06B
LAGUNA CITY PH 02 BLK 25
METRO TOWN PH 01 BLK 02
METRO CITY PH 03 THE METROPOLIS TWR 01
LAGUNA CITY PH 02 BLK 30
LAGUNA CITY PH 01 BLK 16
LAGUNA CITY PH 03 BLK 34
ON NING GDN BLK 03 (PSPS)
PINNACLE BLK 03 (SCHS)
YEN CHING BLDG
LAGUNA CITY PH 02 BLK 31
LAGUNA CITY PH 03 BLK 34
ABERDEEN CTR BLK D HOI WU COURT
ABBA HSE BLK B
COMFORT CTR
ABERDEEN CTR BLK G KONG CHEUNG COURT
FULL JADE MAN
LAGUNA CITY PH 04 BLK 11
SCENEWAY GDN BLK 11
YEN CHING BLDG
VERBENA HTS BLK 01 (FSS)
HIP SING MAN
LAGUNA CITY PH 02 BLK 28
METRO CITY PH 02 TWR 07
FINERY PARK BLK 02
LAGUNA CITY PH 02 BLK 27
FINERY PARK BLK 02
TONG MING COURT BLK C (HOS)
ON FAI BLDG
METRO CITY PH 01 TWR 01
ALTO RESIDENCES TWR 05
KIN FAI BLDG
METRO CITY PH 01 TWR 04
LAGUNA CITY PH 01 BLK 04
SCENEWAY GDN BLK 11
NGAN FUNG BLDG
YUE FAI COURT BLK C (HOS)
HUNG FOOK COURT
SOUTH COAST
BEVERLY GDN PH 01 BLK 03 (PSPS)
EAST POINT CITY BLK 02
LAGUNA CITY PH 04 LAGUNA COVE BLK 12
SCENEWAY GDN BLK 02
LAGUNA CITY PH 03 BLK 33
LAGUNA CITY PH 01 BLK 07
LAGUNA CITY PH 02 BLK 29
LAGUNA CITY PH 01 BLK 05
KIN FAI BLDG
YUE FAI COURT BLK B (HOS)
HONG SING GDN BLK 05 (PSPS)
LAGUNA CITY PH 01 BLK 05
LEE FAT BLDG
LAGUNA CITY PH 02 BLK 31
H BONAIRE
METRO CITY PH 03 THE METROPOLIS TWR 02
YING MING COURT BLK C MING TAT HSE (HOS)
YUE FAI COURT BLK B (HOS)
SCENEWAY GDN BLK 06
METRO CITY PH 01 TWR 03
OCEAN HSE
METRO CITY PH 03 THE METROPOLIS TWR 01
LAGUNA CITY PH 03 BLK 37
KIN FAI BLDG
LAGUNA CITY PH 04 BLK 11
JING HUI GDN BLK 02
MARITIME BAY BLK 01
LAGUNA CITY PH 01 BLK 01
LAGUNA CITY PH 01 BLK 14
LAGUNA CITY PH 03 BLK 38
LAGUNA CITY PH 01 BLK 06
LAGUNA CITY PH 02 BLK 30
SCENEWAY GDN BLK 16
LAGUNA CITY PH 02 BLK 27
METRO CITY PH 01 TWR 05
ON FAI BLDG
LAGUNA CITY PH 01 BLK 04
SCENEWAY GDN BLK 02
METRO CITY PH 02 TWR 03
LAGUNA CITY PH 04 LAGUNA COVE BLK 21
LAGUNA CITY PH 04 BLK 22
METRO CITY PH 03 THE METROPOLIS TWR 04
GRANDVIEW GDN BLK 02
COMFORT CTR
COMFORT CTR
KING MING COURT BLK A HEI KING HSE (HOS)
PO MING COURT BLK A (HOS)
SCENEWAY GDN BLK 16
MARITIME BAY BLK 01
YUE ON COURT BLK D (HOS)
LAGUNA CITY PH 04 BLK 18
WAI KING MAN
COMFORT CTR
COBLE COURT
KIN FAI BLDG
SCENEWAY GDN BLK 16
LA CITE NOBLE BLK 01
KA WO BLDG BLK A
METRO CITY PH 02 TWR 02
GRANDIOSE BLK 01
YUE FAI COURT BLK C (HOS)
LAGUNA CITY PH 03 BLK 34
FINERY PARK BLK 01
ABERDEEN CTR BLK M HOI TIN COURT
KWONG MING COURT PH 01 BLK D (HOS)
LAGUNA CITY PH 04 LAGUNA COVE BLK 12
GRANDIOSE BLK 02
LA CITE NOBLE BLK 02
TONG MING COURT BLK B (HOS)
KA LUNG COURT BLK B KA PING HSE (HOS)
EAST POINT CITY BLK 05
ALBERT HSE
ABBA HSE BLK A
ABERDEEN CTR BLK P MEI KWONG COURT
WELL ON GDN BLK 04
YAN MING COURT BLK E (HOS)
ABERDEEN CTR BLK C HOI SHAN COURT
YUE FAI COURT BLK F (HOS)
KWONG MING COURT PH 01 BLK D (HOS)
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
LAGUNA CITY PH 03 BLK 32
LAGUNA CITY PH 01 BLK 05
ABBA HSE BLK B
SCENEWAY GDN BLK 07
LAGUNA CITY PH 01 BLK 01
ABERDEEN CTR BLK E KONG FU COURT
ABERDEEN CTR BLK I KONG WING COURT
TUNG NAM BLDG
SOUTH WALK AURA
LAGUNA CITY PH 02 BLK 30
EAST POINT CITY BLK 02
BEVERLY GDN PH 02 BLK 05 (PSPS)
TONG MING COURT BLK A (HOS)
YING MING COURT BLK A MING YUEN HSE (HOS
PELENE MAN
YU MING COURT PH 01 BLK B (HOS)
YING MING COURT BLK A MING YUEN HSE (HOS
LOHAS PARK PH 02 TWR 02 LEFT
GRANDIOSE BLK 02
KWONG MING COURT PH 01 BLK G (HOS)
PO LAM EST BLK 01 PO YAN HSE
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
BILLION COURT
YING MING COURT BLK C MING TAT HSE (HOS)
TSEUNG KWAN O PLAZA PH 01 TWR 03
FINERY PARK BLK 02
PARK CENTRAL PH 01 TWR 06
KONG KAI BLDG
NING FUNG MAN
LAGUNA CITY PH 04 BLK 19
LAGUNA CITY PH 02 BLK 24
LAGUNA CITY PH 04 LAGUNA COVE BLK 21
LAGUNA CITY PH 04 LAGUNA COVE BLK 20
LAGUNA CITY PH 04 BLK 18
LAGUNA CITY PH 01 BLK 02
LAGUNA CITY PH 02 BLK 30
LAGUNA CITY PH 01 BLK 13
LAGUNA CITY PH 03 BLK 38
LAGUNA CITY PH 02 BLK 25
LAGUNA CITY PH 01 BLK 14
METRO CITY PH 03 THE METROPOLIS TWR 01
ABERDEEN CTR BLK A HOI CHUN COURT
LAGUNA CITY PH 04 LAGUNA COVE BLK 10
ABERDEEN HARBOUR MANS
NAN FUNG PLAZA TWR 06
LOHAS PARK PH 07A MONTARA TWR 02B
OSCAR BY THE SEA BLK 07
ABBA HSE BLK A
LAGUNA CITY PH 02 BLK 30
SCENEWAY GDN BLK 16
PO MING COURT BLK B (HOS)
ABERDEEN CTR BLK G KONG CHEUNG COURT
TWIN PEAKS TWR 02
YEE TIAM BLDG
HONG SING GDN BLK 03 (PSPS)
PO MING COURT BLK B (HOS)
LAGUNA CITY PH 01 BLK 15
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
MOSBERT MAN
LA CITE NOBLE BLK 05
PO MING COURT BLK A (HOS)
KAM FUNG BLDG
SOUTH COAST
METRO CITY PH 01 TWR 05
KAM FUNG BLDG
PELENE MAN
SERENITY PLACE BLK 02
SOUTH WALK AURA
FU NING GDN BLK 03 (PSPS)
LAGUNA CITY PH 04 LAGUNA COVE BLK 20
SCENEWAY GDN BLK 08
TONG MING COURT BLK C (HOS)
KIN FAI BLDG
LAGUNA CITY PH 01 BLK 02
PAT LEUNG BLDG
ABERDEEN CTR BLK M HOI TIN COURT
NAN FUNG PLAZA TWR 06
METRO CITY PH 02 TWR 03
LAGUNA CITY PH 01 BLK 14
LAGUNA CITY PH 04 LAGUNA COVE BLK 10
LAGUNA CITY PH 01 BLK 17
METRO CITY PH 01 TWR 04
LA CITE NOBLE BLK 04
EAST POINT CITY BLK 06
FINERY PARK BLK 02
LAGUNA CITY PH 04 BLK 18
KING LAM EST BLK 06 KING TAO HSE
ABERDEEN CTR BLK B HOI CHU COURT
METRO CITY PH 01 TWR 03
FINERY PARK BLK 02
METRO CITY PH 01 TWR 01
LOHAS PARK PH 09A MARINI TWR 03A
JING HUI GDN BLK 01
ON NING GDN BLK 04 (PSPS)
PARK CENTRAL PH 01 TWR 07
PARK CENTRAL PH 01 TWR 07
LAGUNA CITY PH 01 BLK 16
TSEUNG KWAN O PLAZA PH 02 TWR 08
OCEAN SHORES PH 03 TWR 16
SCENEWAY GDN BLK 02
WELL ON GDN BLK 02
LAGUNA CITY PH 03 BLK 33
LAGUNA CITY PH 02 BLK 27
GRANDVIEW GDN BLK 02
LOHAS PARK PH 08 SEA TO SKY TWR 03
METRO CITY PH 02 TWR 07
KA WO BLDG BLK A
MARITIME BAY BLK 01
LAGUNA CITY PH 04 BLK 09
LOHAS PARK PH 08 SEA TO SKY TWR 02
ABERDEEN CTR BLK M HOI TIN COURT
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
LOHAS PARK PH 07A MONTARA TWR 02A
SERENITY PLACE BLK 02
LOHAS PARK PH 06 LP6 TWR 03
NING FUNG MAN
SERENITY PLACE BLK 01
LAGUNA CITY PH 01 BLK 07
LAGUNA CITY PH 01 BLK 02
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
LAGUNA CITY PH 04 BLK 19
LAGUNA CITY PH 04 BLK 19
LAGUNA CITY PH 03 BLK 38
LAGUNA CITY PH 04 BLK 18
LAGUNA CITY PH 01 BLK 13
LAGUNA CITY PH 02 BLK 26
LAGUNA CITY PH 01 BLK 02
LAGUNA CITY PH 04 LAGUNA COVE BLK 21
LAGUNA CITY PH 01 BLK 02
METRO CITY PH 02 TWR 07
LAGUNA CITY PH 02 BLK 25
LAGUNA CITY PH 01 BLK 07
LOHAS PARK PH 06 LP6 TWR 03
METRO CITY PH 01 TWR 01
PARK CENTRAL PH 02 TWR 11
METRO CITY PH 03 THE METROPOLIS TWR 03
PO MING COURT BLK B (HOS)
METRO CITY PH 01 TWR 02
KING MING COURT BLK B FAI KING HSE (HOS)
ABERDEEN CTR BLK J KONG HING COURT
SOUTH WALK AURA
LAGUNA CITY PH 04 LAGUNA COVE BLK 12
ABERDEEN CTR BLK H KONG TAI COURT
ABBA HSE BLK B

LAGUNA CITY PH 01 BLK 07
LAGUNA CITY PH 04 BLK 18
LAGUNA CITY PH 01 BLK 05
LAGUNA CITY PH 04 LAGUNA COVE BLK 10
ABERDEEN CTR BLK M HOI TIN COURT
YUE FAI COURT BLK E (HOS)
TSUI LAM EST BLK 06 FAI LAM HSE
SOUTH WALK AURA
LAGUNA CITY PH 01 BLK 07
LAGUNA CITY PH 04 LAGUNA COVE BLK 12
LAGUNA CITY PH 02 BLK 29
HONG SING GDN BLK 03 (PSPS)
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
LAGUNA CITY PH 01 BLK 05
LAGUNA CITY PH 04 LAGUNA COVE BLK 21
MARINA HABITAT BLK 02 (SCHS)
LAGUNA CITY PH 01 BLK 01
TOHO COURT
LOHAS PARK PH 07A MONTARA TWR 02A
VERBENA HTS BLK 05 (FSS)
KING LAM EST BLK 02 KING LUI HSE
PO MING COURT BLK B (HOS)
PINNACLE BLK 02 (SCHS)
THE WINGS IIIB TWR 01A
THE WINGS IIIB TWR 01A
PINNACLE BLK 04 (SCHS)
BEVERLY GDN PH 02 BLK 08 (PSPS)
METRO CITY PH 03 THE METROPOLIS TWR 04
KAM FUNG BLDG
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
SERENITY PLACE BLK 05
PINNACLE BLK 04 (SCHS)
LAGUNA CITY PH 03 BLK 33
KING LAM EST BLK 08 KING YUNG HSE
SERENITY PLACE BLK 02
LAGUNA CITY PH 01 BLK 04
LAGUNA CITY PH 01 BLK 07
METRO CITY PH 02 TWR 11
LOHAS PARK PH 07A MONTARA TWR 02A
HONG SING GDN BLK 03 (PSPS)
YEE HING BLDG
YEE HING BLDG
TSEUNG KWAN O PLAZA PH 01 TWR 3A
TSEUNG KWAN O PLAZA PH 01 TWR 02
TSEUNG KWAN O PLAZA PH 02 TWR 08
ON FAI BLDG
LAGUNA CITY PH 01 BLK 01
LAGUNA CITY PH 02 BLK 29
LAGUNA CITY PH 04 LAGUNA COVE BLK 10
LAGUNA CITY PH 04 LAGUNA COVE BLK 12
LAGUNA CITY PH 02 BLK 27
LAGUNA CITY PH 01 BLK 02
LAGUNA CITY PH 02 BLK 30
LAGUNA CITY PH 01 BLK 16
LAGUNA CITY PH 01 BLK 06
LAGUNA CITY PH 02 BLK 29
ABERDEEN HARBOUR MANS
LAGUNA CITY PH 01 BLK 08
LAGUNA CITY PH 01 BLK 16
TIN WAN COURT
LEI TUNG EST TUNG PING HSE
SCENEWAY GDN BLK 07
LOHAS PARK PH 09A MARINI TWR 03B
METRO CITY PH 02 TWR 10
LAGUNA CITY PH 02 BLK 27
LAGUNA CITY PH 04 LAGUNA COVE BLK 12
SCENEWAY GDN BLK 12

TSUI LAM EST BLK 02 SAU LAM HSE
YU MING COURT PH 01 BLK B (HOS)
FINERY PARK BLK 01



METRO CITY PH 01 TWR 02

SCENEWAY GDN BLK 07
LOHAS PARK PH 06 LP6 TWR 05
GRANDIOSE BLK 03

METRO CITY PH 01 TWR 03
RADIANT TWRS BLK 01 (SCHS)
VERBENA HTS BLK 03 (FSS)
LAGUNA CITY PH 03 BLK 32
SCENEWAY GDN BLK 01
FULL JADE MAN
LOHAS PARK PH 02 TWR 05 LEFT
HONG SING GDN BLK 04 (PSPS)
LAGUNA CITY PH 04 BLK 22
ABERDEEN CTR BLK I KONG WING COURT
YUE ON COURT BLK A (HOS)
ABERDEEN CTR BLK L HOI YING COURT
LA CITE NOBLE BLK 03
LAGUNA CITY PH 03 BLK 34
LAGUNA CITY PH 03 BLK 36
COBLE COURT
METRO CITY PH 02 TWR 02
LAGUNA CITY PH 01 BLK 02
GRANDVIEW GDN BLK 01
METRO CITY PH 02 TWR 10
LAGUNA CITY PH 02 BLK 29
SCENEWAY GDN BLK 07
LAGUNA CITY PH 04 BLK 19
HUNG FOOK COURT
METRO CITY PH 02 TWR 10
WELL ON GDN BLK 04
METRO CITY PH 02 TWR 07
SCENEWAY GDN BLK 06
METRO CITY PH 03 THE METROPOLIS TWR 02
GRANDIOSE BLK 02
PARK CENTRAL PH 02 TWR 10
KING LAM EST BLK 08 KING YUNG HSE
LOHAS PARK PH 06 LP6 TWR 05
LAGUNA CITY PH 04 LAGUNA COVE BLK 21
LAGUNA CITY PH 01 BLK 06
FINERY PARK BLK 01
METRO CITY PH 01 TWR 03
METRO CITY PH 02 TWR 11
HONG SING GDN BLK 05 (PSPS)
VENG HING MAN
ON TAI BLDG
WATERFRONT SOUTH BLK 02
YU MING COURT PH 02 BLK A (HOS)
YEN CHING BLDG
TSEUNG KWAN O PLAZA PH 01 TWR 03
MARINA HABITAT BLK 01 (SCHS)
RADIANT TWRS BLK 02 (SCHS)
WATERFRONT SOUTH BLK 02
METRO CITY PH 03 THE METROPOLIS TWR 01
SCENEWAY GDN BLK 07
LAGUNA CITY PH 01 BLK 07
CHOI MING COURT BLK B (HOS)
METRO CITY PH 01 TWR 02
TSEUNG KWAN O PLAZA PH 01 TWR 3A
LAGUNA CITY PH 04 LAGUNA COVE BLK 23
SCENEWAY GDN BLK 04
COMMAND TWR
YING MING COURT BLK E MING ON HSE (HOS)
YUE ON COURT BLK A (HOS)
METRO CITY PH 03 THE METROPOLIS TWR 04
METRO CITY PH 03 THE METROPOLIS TWR 01
TOHO COURT
VERBENA HTS BLK 04 (FSS)
LAGUNA CITY PH 02 BLK 24
THE WINGS II TWR 05B
THE WINGS TWR 03 LUNA DIAMOND
THE WINGS IIIA TWR 05A
PARK CENTRAL PH 02 TWR 12
VERBENA HTS BLK 05 (FSS)
WELL ON GDN BLK 02
LOHAS PARK PH 06 LP6 TWR 03
YUE ON COURT BLK D (HOS)
LAGUNA CITY PH 03 BLK 36
LAGUNA CITY PH 03 BLK 36
TSEUNG KWAN O PLAZA PH 01 TWR 3A
H BONAIRE
GRANDIOSE BLK 03
LOHAS PARK PH 06 LP6 TWR 05
ON NING GDN BLK 01 (PSPS)
RADIANT TWRS BLK 02 (SCHS)
PO MING COURT BLK B (HOS)
VERBENA HTS BLK 05 (FSS)
METRO CITY PH 02 TWR 09
VERBENA HTS BLK 03 (FSS)
JUMBO COURT
COBLE COURT
METRO CITY PH 03 THE METROPOLIS TWR 01
EAST POINT CITY BLK 02
KING MING COURT BLK A HEI KING HSE (HOS)
TONG MING COURT BLK B (HOS)
METRO CITY PH 01 TWR 02
PARK CENTRAL PH 03 TWR 13
LAGUNA CITY PH 04 BLK 09
METRO CITY PH 02 TWR 05
BEVERLY GDN PH 01 BLK 03 (PSPS)
OCEAN WINGS TWR 07A
PARK CENTRAL PH 02 TWR 02
YAN MING COURT BLK D (HOS)
TONG MING COURT BLK C (HOS)
CHUNG MING COURT BLK B FAI MING HSE (HOS
ABERDEEN CTR BLK J KONG HING COURT
THE PAPILLONS TWR 05
YUE FAI COURT BLK B (HOS)
HIN MING COURT (HOS)

ABERDEEN CTR BLK T KWUN CHIU COURT
SOUTH COAST
MARINA HABITAT BLK 02 (SCHS)
CHOI MING COURT BLK E (HOS)
METRO CITY PH 02 TWR 10

METRO CITY PH 02 TWR 11
KAM FAT BLDG
FINERY PARK BLK 01
METRO CITY PH 02 TWR 10
ABERDEEN CTR BLK B HOI CHU COURT
CHOI MING COURT BLK E (HOS)
FORTUNE MAN
ALBERT HSE
ABERDEEN CTR BLK I KONG WING COURT
CORINTHIA BY THE SEA TWR 02
THE WINGS IIIA TWR 05A
THE BEAUMOUNT TWR 07
BEVERLY GDN PH 01 BLK 01 (PSPS)
NAN FUNG PLAZA TWR 02
ON TAI BLDG
NAN FUNG PLAZA TWR 06
NAN FUNG PLAZA TWR 02
METRO CITY PH 02 TWR 07
LOHAS PARK PH 06 LP6 TWR 01
LOHAS PARK PH 07A MONTARA TWR 02A

In [416]:
df[df["District2"] != ""].count()

Date                  521
Building / Address    521
Floor                 521
SA (ft2)              521
Price(HK$)            521
Price/ft2(SA)         521
District1             521
District2             521
dtype: int64

In [425]:
test = pd.read_csv("./Data.csv")
test

,address,full_address,subdistrict_name,dc_name_15,dc_name_19,lat,lng,name
0,JADEWATER,香港仔大道 238號,香港仔,香港仔 (D01),香港仔 (D01),22.2486,114.1521,南灣御園
1,METRO CITY PH 01 TWR 02,"37-38 UG., METRO CITY PLAZA , PHASE 2, TSEUNG ...",寶琳,欣英 (Q18),欣英 (Q19),22.3232,114.2577,新都城中西藥房有限公司
2,THE BEAUMOUNT TWR 06,峻瀅ＩＩ,康城,環保北 (Q26),環保北 (Q28),22.2965,114.2745,The Beaumount II Tower 1
3,BEVERLY GDN PH 02 BLK 09 (PSPS),富康花園,將軍澳,富君 (Q12),富君 (Q12),22.3110,114.2611,富康花園第一座
4,LAGUNA CITY PH 03 BLK 37,九龍觀塘茶果嶺道 91號麗港城第二期地下低層一樓幼稚園部分,鯉魚門,麗港城 (J25),麗港城 (J27),22.3062,114.2288,迦南幼兒園(麗港城)
...,...,...,...,...,...,...,...,...
516,NAN FUNG PLAZA TWR 06,新界將軍澳地段２３號南豐廣場幼稚園基座部份地下及平台一樓（包括幼兒中心）,坑口,南安 (Q14),南安 (Q26),22.3150,114.2640,綠茵英文（國際）幼稚園（將軍澳）
517,NAN FUNG PLAZA TWR 02,新界將軍澳地段２３號南豐廣場幼稚園基座部份地下及平台一樓（包括幼兒中心）,坑口,南安 (Q14),南安 (Q26),22.3150,114.2640,綠茵英文（國際）幼稚園（將軍澳）
518,METRO CITY PH 02 TWR 07,"37-38 UG., METRO CITY PLAZA , PHASE 2, TSEUNG ...",寶琳,欣英 (Q18),欣英 (Q19),22.3232,114.2577,新都城中西藥房有限公司
519,LOHAS PARK PH 06 LP6 TWR 01,"SHOP F14A-15A, TELFORD PLAZA PH 1, KOWLOON BAY...",九龍灣,九龍灣 (J02),九龍灣 (J02),22.3216,114.2131,CHEUNG FUNG DISPENSARY AND SUPERMARKET LTD.
520,LOHAS PARK PH 07A MONTARA TWR 02A,"SHOP F14A-15A, TELFORD PLAZA PH 1, KOWLOON BAY...",九龍灣,九龍灣 (J02),九龍灣 (J02),22.3216,114.2131,CHEUNG FUNG DISPENSARY AND SUPERMARKET LTD.

In [365]:
#df.to_csv("cleaned_cnp 3-yrs_web-scrap_v2.csv")